Manually clean up Particle System Components spawned into Emitter Pool by X2UnifiedProjectile
X2CommunityCore/X2WOTCCommunityHighlander pull request #1013
Opened 2021-06-10 09:51 UTC by Iridar

Closes #720 

Let me know of comments are insufficient or we need docs. Or a ref:bugfix tag.

2021-06-10 10:15 UTC, Xymanek reviewed
Why `class'WorldInfo'.static.GetWorldInfo()` instead of just `WorldInfo`?

2021-06-10 10:17 UTC, Iridar commented
> Why `class'WorldInfo'.static.GetWorldInfo()` instead of just `WorldInfo`?

Didn't know it was an option, I'm not familiar with WorldInfo so I dunno where it exists. I'll adjust.

2021-06-10 10:18 UTC, Xymanek commented
Regarding the docs: IMO this deserves a separate page because there is tons of explanation to present the full chain of events and there are more than 1 places in code which were changed

2021-06-10 10:19 UTC, Iridar commented
Alright, I'll add some docs then.

2021-06-10 13:36 UTC, Iridar commented
Added docs.

2021-06-10 15:45 UTC, Xymanek requested changes

2021-06-10 15:45 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			/// on PSCs in `X2UnifiedProjectile` when it's time for them to be removed.
That's not a correct explanation/understand of how an object pool works. Here's a better one:

> When a PSC is "done", it is returned to the pool so that it can be reused again later.
> 
> To return a PSC back to the pool, the `EmitterPool::OnParticleSystemFinished()` function must be called, which usually happens seamlessly - the pool sets the `ParticleSystemComponent::OnSystemFinished` delegate to the aforementioned function when the PSC is initially borrowed from the pool (via `EmitterPool::SpawnEmitter`).
> 
> However, `X2UnifiedProjectile` overwrites the `OnSystemFinished` delegate with its own one (after borrowing the PSC), which means the `EmitterPool::OnParticleSystemFinished()` is never called for these PSCs. As such, the pool is never made aware that those PSCs are ready for reuse and when a new PCS is requested, the pool has no choice but to simply create a new one, resulting in the pool getting bloated with all the PSCs ever spawned by `X2UnifiedProjectile`s.
> 
> This bloat leads to 2 observable effects: endlessly increasing RAM usage and a significant performance degradation, especially if there are a lot of shots fired during a mission, particularly if the squad and enemy pods have increased sizes and/or the mission is long. Frequent use of the Suppression ability or Idle Suppression mod kick the problem into overdrive.
> 
> To address this bug, we manually call `WorldInfo.MyEmitterPool.OnParticleSystemFinished()` on PSCs in `X2UnifiedProjectile` when the projectile is done with them.

That said, I'm not a huge fan of phrasing (especially the `[...] especially [...], particularly [...]`) so I would prefer some editorial work on it first

2021-06-10 15:47 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			/// on PSCs in `X2UnifiedProjectile` when it's time for them to be removed.
Okay, I'll adjust.

2021-06-10 16:39 UTC, Iridar commented
Adjusted docs, how's that?

2021-06-10 18:03 UTC, Xymanek reviewed
I think it's also a good idea to add a paragraph about X2UP subclasses - they might need to do the same if they manually create/destroy PSCs or overwrite the fixed functions

2021-06-10 18:03 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			/// these effects become.  Frequent use of the Suppression ability or Idle Suppression mod
```suggestion
			/// these effects become. Frequent use of the Suppression ability or Idle Suppression mod 
```

2021-06-10 18:45 UTC, Iridar commented
> I think it's also a good idea to add a paragraph about X2UP subclasses - they might need to do the same if they manually create/destroy PSCs or overwrite the fixed functions

Will do, although we don't have anything to worry too much about anyone doing that, support for subclasses of X2UnifiedProjectile has only recently became available, and to best of my knowledge only Musashi and I took advantage of it.

2021-06-10 18:49 UTC, Iridar commented
Though point actually stands for *all* PSCs created into the Pool.

2021-06-11 06:29 UTC, Xymanek commented
The reason I mentioned X2UP subclasses is that overriding a fixed function without re-applying the fix will bring the issue back. That said, perhabs a better place to mention this is the `OverrideProjectileInstance` documentation (i.e. just add a mention/link to `ProjectilePerformanceDrain`).

2021-06-11 06:30 UTC, Iridar commented
> The reason I mentioned X2UP subclasses is that overriding a fixed function without re-applying the fix will bring the issue back. That said, perhabs a better place to mention this is the `OverrideProjectileInstance` documentation (i.e. just add a mention/link to `ProjectilePerformanceDrain`).

Do you want me to do this within this PR?

2021-06-11 06:30 UTC, Xymanek commented
Yes

2021-06-11 07:50 UTC, Iridar commented
> Yes

Doneso.

2021-06-11 08:23 UTC, Xymanek approved these changes

2021-06-16 06:01 UTC, merged