Reorder evac of carrying and carried units (#1027)
X2CommunityCore/X2WOTCCommunityHighlander pull request #1028
Opened 2021-06-20 14:22 UTC by pledbrook

In order to ensure that Kismet properly handles units that are carried when evacuated, this change processes the evacuation of the carried unit first. Note that this only changes the `SeqEvent_EvacActivated` Kismet node.

Fixes #1027.

2021-06-23 04:12 UTC, Iridar approved these changes
Looks good to me, but are we absolutely sure the IterateByClassType will give us state objects in the order they were added to the game state? And if so, perhaps we could change the place in code where evacing units are being added to the game state instead?

2021-06-23 08:07 UTC, pledbrook commented
Unfortunately (or fortunately?) the soldier whose evac ability gets activated is guaranteed to be the first one in the new game state. I tried changing the order that units were added to the game state in `XCGS_Unit.EvacuateUnit()`, but it had no effect because of that.

2021-06-24 15:23 UTC, pledbrook commented
> Looks good to me, but are we absolutely sure the IterateByClassType will give us state objects in the order they were added to the game state? And if so, perhaps we could change the place in code where evacing units are being added to the game state instead?

I looked into being defensive and ordering the evac based on whether a unit is being carried or not, but the "carried" effect is removed by the time we get to this code. We could infer that unconscious units are being carried, so order based on that, but I don't know if that's any more reliable than assuming game state objects are iterated over in the order that they are added to the game state.

@tracktwo Any thoughts?

2021-06-24 16:31 UTC, tracktwo commented
Maybe check the unit template for hostile VIP (or, any non-soldier) and order those first?

This really is at it's root a kismet bug in the neutralize VIP mission, but that's harder to fix at the root in the highlander. Specifically patching for this particular bug on this mission type seems reasonable to me, rather than trying to define a more general solution. Anyone else writing custom missions that rely on order of extraction should write kismet that doesn't have bugs like this. I'd only suggest going further with the generalization if there are existing modded missions out there that copied the same bug from Neutralize VIP and are no longer being updated.

2021-06-25 08:17 UTC, pledbrook commented
> This really is at its root a kismet bug in the neutralize VIP mission

Is that true? I'm just wondering what happens in cases where a VIP on a rescue or extract mission is carried out. Would they be awarded at the end of the mission with the current code? And since modders will often just copy base-game stuff, one can expect the same sorts of issues to appear in modded missions.

My gut feeling is that ensuring EvacActivated is fired for carried units first will simplify the Kismet for missions. hence why I'd prefer a more general solution rather than one narrowly focused on the Neutralize VIP mission. That said, I still don't understand how the reward code works, or whether "Team out of playable units" fires in between the EvacActivated events for carried and carry units.

2021-06-25 10:40 UTC, Xymanek requested changes
I'm 👎 for relying on iteration order of states inside a frame. There are no documented guarantees, it's not used anywhere like that and reordering some preceding logic (or having a just "right" listener from a mod) can easily cause this "fix" to fall apart

2021-06-25 16:07 UTC, tracktwo commented
> Is that true? I'm just wondering what happens in cases where a VIP on a rescue or extract mission is carried out.

I can't definitively say such a bug doesn't exist, but the evidence I have against it is I've seen the neutralize VIP bug reported regularly on evac all after the bug was introduced (with DLC3) but never any other similar bug for other mission types. The first bug report I got on evac all for this was 2016-06-30, which is the same day SLG released, and it blew up the mod page for a bit. Similarly I "fixed" the bug with a patched kismet sequence in the original evac all, and after that the bug stopped being reported, except for people using mods that also replaced that mission map (e.g. to extend/remove timers) and reintroduced the bug.

My initial analysis of this bug was back in that time frame and in vanilla, so it's also possible that I'm misremembering details and/or if WoTC has changed things, but IIRC the reward for the hostile VIP (and others) is based only off whether the corresponding objective is marked as complete in kismet and the unit state is not 'dead' (`XCGS_MissionSite.GetRewardVIPStatus`). It's specifically relevant for neutralize VIP missions because the _only_ way to get a hostile VIP out is to carry them, extract VIPs are player-controlled on the XCOM team and so don't need to have kismet checks to make sure there are other units still around able to extract the unit. The path in kismet for setting this strategy objective as complete is short-circuited and ends without marking the objective complete if the Mission.VIPKilled variable is true, and this variable is set when the last soldier evacs. Killing the VIP when the last XCOM unit extracts was added to avoid mission failure in SLG: if you extract all your humans but leave the VIP on the ground while still having SPARKs you've hard failed the mission because sparks can't pick up the VIP, but they also can't shoot the unconscious VIP to complete the 'kill' objective.

I've lived with this bug for over 5 years now, and the current workaround in Evac All is 'good enough' for me in that it solves the vast majority of cases, but it surely would be nice to have this fixed completely in the highlander and it seems to me to fit the highlander mandate of fixing vanilla bugs.

2021-07-29 08:12 UTC, pledbrook commented
I'm currently considering whether to check for "unconscious" or "hostile VIP". I'm pretty sure "unconscious" is the only state that allows living units to be carried. It covers the Neutralize VIP mission while providing cover for other mission types with similar problems that are perhaps just more rarely encountered. Any downsides to that approach that folks can see?

2021-07-29 09:54 UTC, Iridar commented
> I'm currently considering whether to check for "unconscious" or "hostile VIP". I'm pretty sure "unconscious" is the only state that allows living units to be carried. It covers the Neutralize VIP mission while providing cover for other mission types with similar problems that are perhaps just more rarely encountered. Any downsides to that approach that folks can see?

Unless I'm missing something, a simple good solution would be something like:

```
foreach GameState.IterateByClassType(class'XComGameState_Unit', RelevantUnit)
{
	if (RelevantUnit.IsBeingCarried())
	{
		CarriedUnits.AddItem(RelevantUnit);
	}
	else
	{
		OtherUnits.AddItem(RelevantUnit);
	}
}

foreach CarriedUnits(RelevantUnit)
{
	CheckActivate(RelevantUnit.GetVisualizer(), none);
}

foreach OtherUnits(RelevantUnit)
{
	CheckActivate(RelevantUnit.GetVisualizer(), none);
}
```

2021-07-29 09:56 UTC, Iridar commented
Personally I'd prefer some kind of definitive check of "Was unit being carried when Evac was activated".

2021-07-29 10:09 UTC, Xymanek commented
Just a reminder that the history system allows looking all the way back to the start of the battle

2021-08-09 13:39 UTC, pledbrook commented
If anyone can provide the code for getting an appropriate history index, for example the start of the turn on which the carried unit was evac'ed out on, then I'll happily add it in. Can't work it out myself at the moment.

2023-05-21 07:59 UTC, Iridar commented
Since the author has bSince no progress has been made for ~two years, I'm archiving this.een AWOL for over two years, I'm archiving this.

2023-05-21 07:59 UTC, closed without merging