Allow mods to override which alerts Can be triggered outside of player vision
X2CommunityCore/X2WOTCCommunityHighlander pull request #1037
Opened 2021-07-11 16:03 UTC by Grobobobo

This implements the hook which allows for that. Solves #1036.

2021-07-11 16:11 UTC, Iridar approved these changes

2021-07-11 16:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +	bResult = OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(AlertCause, bResult);
This could have been implemented as `return OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision()`, but it's a styling nitpick and not necessarily for the better.

2021-07-20 11:55 UTC, Xymanek requested changes

2021-07-20 11:55 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(int AlertCause, bool AllowThisCause)
Why `int` and not `EAlertCause`?

2021-07-20 12:03 UTC, Grobobobo commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(int AlertCause, bool AllowThisCause)
Well, it's saved in the tuple as int, right?

2021-07-20 12:10 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(int AlertCause, bool AllowThisCause)
Check this as an example, since it also passed an enum to the listeners:

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/fb6622d26fdae062153f9bad20b692a69705b1b1/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc#L1550-L1558

2021-07-20 14:22 UTC, Grobobobo commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(int AlertCause, bool AllowThisCause)
I've changed it, though issue 510 uses EAlertCause as an int, which I used as an example.

2021-07-24 13:18 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(int AlertCause, bool AllowThisCause)
> issue 510 uses EAlertCause as an int, which I used as an example

It's unfortunate that this issue wasn't caught there, but it doesn't mean that we should keep propagating the subpar option

> I've changed it

I see the change to docs (👍) but not to the function signature

2021-07-24 14:27 UTC, Grobobobo commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(int AlertCause, bool AllowThisCause)
Done

2021-08-09 14:16 UTC, pledbrook requested changes
Added suggestions for consistency. Also clarity in the docs.

2021-08-09 14:16 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +	bResult = OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(AlertCause, bResult);
For consistency with other event-firing functions (`Trigger<EventName>()`):
```suggestion
	bResult = TriggerOverrideEnemyFactionsAlertsOutsideVision(AlertCause, bResult);
```

2021-08-09 14:16 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +/// AlertCause Contains the Alert Value, while AllowThisCause boolean Determines if the alert is allowed.
```suggestion
/// Fires an event that allows listeners to override whether a given alert cause
/// can be triggered by AI units outside of XCOM's vision. For example, you could
/// use this event to allow enemy pods to activate one another outside of XCOM
/// vision for a given set of alert causes.
///
/// Return `true` in `bResult` if the alert cause can be triggered in such
/// situations. Leave `bResult` untouched to retain the default behavior.
```

2021-08-09 14:16 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool OverrideShouldEnemyFactionsTriggerAlertsOutsidePlayerVision(EAlertCause AlertCause, bool AllowThisCause)
As per previous comment on consistency:
```suggestion
static function bool TriggerOverrideEnemyFactionsAlertsOutsideVision(EAlertCause AlertCause, bool AllowThisCause)
```

2021-08-09 14:16 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +	return  OverrideTuple.Data[1].b;
```suggestion
	return OverrideTuple.Data[1].b;
```

2021-08-09 14:16 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +/// EventData: [ in enum[EAlertCause] AlertCause, inout bool bResult],
Might make sense to change `bResult` to `AllowThisCause` and update the event description above. It's certainly easier to understand what `AllowThisCause` is for compared to `bResult`.

2021-11-23 15:38 UTC, Xymanek approved these changes

2021-11-23 15:39 UTC, Xymanek requested changes

2021-11-23 15:39 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIUnitData.uc
> +static function bool TriggerOverrideEnemyFactionsAlertsOutsideVision(EAlertCause AlertCause, bool AllowThisCause)
```suggestion
static private function bool TriggerOverrideEnemyFactionsAlertsOutsideVision(EAlertCause AlertCause, bool AllowThisCause)
```

2021-11-24 07:05 UTC, Xymanek approved these changes

2021-11-24 07:05 UTC, merged