Make GetUISummary_UnitStatusIcons() skip empty status icons
X2CommunityCore/X2WOTCCommunityHighlander pull request #1122
Opened 2022-01-06 09:44 UTC by Iridar

Fixes #1120 

This will fix the bug where status icons would not display sometimes.

2022-01-06 09:59 UTC, Iridar commented
I didn't do a `HLDocs\ref-bugfixes` entry for this one, since there's no room around and I wasn't sure how to handle it.

2022-02-05 10:25 UTC, Xymanek requested changes
Please add `HL-Docs: ref:Bugfixes`

> since there's no room around and I wasn't sure how to handle it

I would put it above the `if`

2022-02-27 06:24 UTC, Iridar commented
Doneso.

2022-02-27 09:37 UTC, Xymanek approved these changes

2022-02-27 09:37 UTC, merged