Allow Mods to disable Popups of New Resistance Order Cards being available
X2CommunityCore/X2WOTCCommunityHighlander pull request #1127
Opened 2022-01-13 15:50 UTC by Grobobobo

Fixes #1126

2022-01-14 06:12 UTC, Iridar requested changes
If this is meant as a global on/off switch for all new cards, whatever they may be, then an event is overkill. IMO this should be done as a config bool flag in CHHelpers.

2022-01-14 09:28 UTC, Grobobobo commented
It's meant as an off switch in my particular case, Someone else may want more conditional changes. Of course I'm more than fine with making it a config variable myself.

2022-01-14 13:12 UTC, Grobobobo commented
Looks like it works now

2022-01-14 13:14 UTC, Iridar approved these changes
LGTM

2022-01-14 13:21 UTC, Grobobobo commented
Ah, wait, now I remember why I made this an event - We have a second wave that enables resistance orders, so the check was supposed to be based on whether that second wave is enabled. That's not possible with a config variable, so I think I should revert to the hook after all. Sorry about that.

2022-01-14 13:25 UTC, Iridar commented
> Ah, wait, now I remember why I made this an event - We have a second wave that enables resistance orders, so the check was supposed to be based on whether that second wave is enabled. That's not possible with a config variable, so I think I should revert to the hook after all. Sorry about that.

If you build against Highlander, you can simply set `class'CHHelpers'.default.YourVarName = true;` in OPTC conditionally.

2022-01-14 13:27 UTC, Grobobobo commented
Huh, I didn't know you could change config variables in runtime. Yeah, then current state is fine.

2022-01-14 13:30 UTC, Grobobobo commented
Although won't you have to keep setting it every time you run the game? I guess it can be set every time on loaded save, and on campaign start.

2022-01-14 13:35 UTC, Iridar commented
> Although won't you have to keep setting it every time you run the game? I guess it can be set every time on loaded save, and on campaign start.

Yeah that's what it would take.

2022-01-15 07:26 UTC, Iridar commented
Per discussion with Xymanek on discord, it was decided that the event is the better approach. Sorry for the wasted work, it be like that sometimes.

2022-01-16 23:56 UTC, Grobobobo commented
I've reverted the changes to the event.

2022-01-18 07:55 UTC, Iridar commented
I think this is good to go, but I'll wait for Xym to confirm.

2022-02-22 11:50 UTC, Xymanek requested changes

2022-02-22 11:50 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_ResistanceFaction.uc
> +		if (NewPlayableCards.Length > 0)
```
if (NewPlayableCards.Length > 0 && /* Issue #1126 */ ShouldDisplayNewCardPopUps())
```

Please do not waste CPU time when there is no need for it

2022-02-22 11:50 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_ResistanceFaction.uc
> +simulated protected function bool ShouldDisplayNewCardPopUps()
```suggestion
simulated private function bool ShouldDisplayNewCardPopUps()
```

2022-02-22 11:50 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_ResistanceFaction.uc
> +	return Tuple.Data[0].b;
Please fix indentation

2022-02-22 11:50 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_ResistanceFaction.uc
> +   `XEVENTMGR.TriggerEvent('UIPopups_DisplayNewCardPopups', Tuple, self, none);
While the current event name isn't problematic, something like `ShouldDisplayNewStrategyCardPopups` would make more sense IMO

2022-06-26 16:20 UTC, Grobobobo commented
I'm Unlikely to use this after all.

2022-06-26 16:20 UTC, closed without merging