Add 'OverrideEligibleTrainingCenterAbilities' event
X2CommunityCore/X2WOTCCommunityHighlander pull request #1129
Opened 2022-01-19 20:03 UTC by Iridar

Closes #815 

This event is a bit non-standard, so looking forward to feedback. 

I tested and it works for the intended purpose of conditionally altering the list of eligible Training Center abilities for each unit.

2022-02-22 11:40 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +/// ```
Something has gone wrong with the generated docs (code sample and the event spec is missing):

![image](https://user-images.githubusercontent.com/2865341/155123432-787cc5a8-0875-4463-82bc-299fb657e666.png)

@robojumper any ideas?

2022-02-22 11:40 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +}
Please move these to `CHHelpers`

2022-02-22 11:40 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	Tuple.Data[2].an = UtilityCats;
I'm not sure about the formatting (first the `kind`s separately and then the values separately) - I would put `SplitSoldierClassAbilityTypeArray` call first and then build the tuple as normal

2022-02-22 11:40 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	`XEVENTMGR.TriggerEvent(Tuple.Id, Tuple, self);
I'm not sure about not passing a gamestate here - this is evidently called inside a state mutation, so right now the listeners don't have a way of retrieving the pending version of unit state. 

Since `RollForTrainingCenterAbilities` itself doesn't receive the pending GameState, you could use this approach: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/8e649638cd623a1e500191e7d09eff3f5dd65c3c/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersAlien.uc#L3328-L3338

2022-02-22 12:17 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +// `RebuildSoldierClassAbilityTypeArray` and `SplitSoldierClassAbilityTypeArray`.
```suggestion
/// `RebuildSoldierClassAbilityTypeArray` and `SplitSoldierClassAbilityTypeArray`.
```

2022-02-27 06:29 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +// `RebuildSoldierClassAbilityTypeArray` and `SplitSoldierClassAbilityTypeArray`.
(Oops)

2022-02-27 09:49 UTC, Xymanek requested changes

2022-02-27 09:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +// End Issue #815
Please keep an empty line at the end of each file

2022-02-27 09:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +	while (i < AbilityNames.Length && i < ApplyToWeaponSlots.Length && i < UtilityCats.Length)
Please add a redscreen in case the sizes of the 3 arrays do not match

2022-02-27 09:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +static final function array<SoldierClassAbilityType> RebuildSoldierClassAbilityTypeArray(const array<name> AbilityNames, const array<int> ApplyToWeaponSlots, const array<name> UtilityCats)
Were these meant to be `const out array<xyz>`?

2022-02-27 09:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +/// ```event
```suggestion
/// ```event,notemplate
```

2022-02-27 09:51 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +static final function array<SoldierClassAbilityType> RebuildSoldierClassAbilityTypeArray(const array<name> AbilityNames, const array<int> ApplyToWeaponSlots, const array<name> UtilityCats)
Sure why not. Let me adjust.

2022-02-27 10:13 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +static final function array<SoldierClassAbilityType> RebuildSoldierClassAbilityTypeArray(const array<name> AbilityNames, const array<int> ApplyToWeaponSlots, const array<name> UtilityCats)
Hmm getting "Not allowed to pass a dynamic array element as the value for an out parameter" cuz of the call:

```
EligibleAbilities = class'CHHelpers'.static.RebuildSoldierClassAbilityTypeArray(Tuple.Data[0].an, Tuple.Data[1].ai, Tuple.Data[2].an);
```
The array in question is `Tuple.Data`, not `Tuple.Data[0].an`. So to bypass this I will have to put the tuple stuff back into local arrays.

2022-02-27 10:20 UTC, Iridar commented
Requested changes implemented.

2022-02-27 10:29 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +static final function array<SoldierClassAbilityType> RebuildSoldierClassAbilityTypeArray(const array<name> AbilityNames, const array<int> ApplyToWeaponSlots, const array<name> UtilityCats)
I assume the problem will plague the provided listener sample

2022-02-27 10:34 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +static final function array<SoldierClassAbilityType> RebuildSoldierClassAbilityTypeArray(const array<name> AbilityNames, const array<int> ApplyToWeaponSlots, const array<name> UtilityCats)
Yeah, it would, great catch. Angler Xymanek.

2022-03-02 09:07 UTC, Xymanek commented
Please force push this branch so that there is 1 commit for adding game files and 1 commit for all the changes

2022-03-02 12:17 UTC, Iridar commented
Feedback addressed, squashed everything into one commit (this PR doesn't add any files).

2022-03-02 12:36 UTC, Xymanek approved these changes

2022-03-02 12:36 UTC, merged