Add event for overriding resistance faction icon #1134
X2CommunityCore/X2WOTCCommunityHighlander pull request #1136
Opened 2022-01-29 03:53 UTC by FearTheBunnies

This is for issue #1134 which will allow mods to override the resistance faction icon when using custom hero classes.

2022-02-14 10:34 UTC, Xymanek requested changes
In many places where you changed `FactionState.GetFactionIcon()` to `UnitState.GetResistanceFactionIcon()`, said code is wrapped into `if (FactionState != none)` - rending the feature useless for non-faction soldiers.

Instead, you should store the result of `UnitState.GetResistanceFactionIcon()` and change the checks to `if (FactionIcon.Images.Length > 0)`

2022-02-14 10:34 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	CustomIcon.Images.Length = 0;
Please fix the indentation

2022-02-14 10:34 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +// the Images array should not start with 'img:///'.
There is no need for these 2 comment "parts". Please put everything under/into `HL-Docs`

2022-02-14 15:30 UTC, FearTheBunnies commented
> In many places where you changed `FactionState.GetFactionIcon()` to `UnitState.GetResistanceFactionIcon()`, said code is wrapped into `if (FactionState != none)` - rending the feature useless for non-faction soldiers.
> 
> Instead, you should store the result of `UnitState.GetResistanceFactionIcon()` and change the checks to `if (FactionIcon.Images.Length > 0)`

Not opposed to changing the check, but was curious your thoughts on it.  Originally that icon was only related to faction heroes, so this change would be expanding the functionality and I am wanting to make sure we're good with that.

2022-02-14 16:44 UTC, Xymanek commented
While I understand the history behind the current setup, I think it's a disservice to the overall flexibility of the system - IMO they should've just converted all icons to stacked (albeit with a single item for traditional class icons). As such, I think it's a good idea to allow the stacked icons to be usable for normal soldiers

2022-02-27 04:40 UTC, FearTheBunnies commented
Updated the logic to make the event more generic so that non-hero soldiers can get the same benefit for having a stacked class icon instead of a flat class icon if a class author so wishes it.  Also cleaned up the other couple of small asks.

2022-02-27 09:53 UTC, Xymanek requested changes

2022-02-27 09:53 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAfterAction_ListItem.uc
> +	local StackedUIIconData StackedClassIcon; // Variable for issue #1134
Please do not remove lines from base game code - simply comment them out (same goes for other instances)

2022-03-02 23:37 UTC, FearTheBunnies commented
Flattened the commit and fixed documentation.

2022-03-03 13:07 UTC, Xymanek approved these changes

2022-03-03 13:07 UTC, merged