Right click melee priority #1138
X2CommunityCore/X2WOTCCommunityHighlander pull request #1139
Opened 2022-02-27 05:37 UTC by FearTheBunnies

This is a pull request to address right-click prioritization when choosing melee skills.  Issue #1138.

2022-02-27 10:22 UTC, Xymanek requested changes
Several overall questions:

1) What happens if same ability has multiple `X2AbilityTrigger_EndOfMove` triggers?
2) What happens if the different dashing melee abilities have different target conditions? E.g. pretty sure I saw dashing medkit somewhere - but the current code doesn't support checking the (potential) target

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +// SECONDARY PRIORITY: Shot HUD Priority low -> high == left -> right in the UI bar
This makes no sense at all to me

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +var int RClickMeleePriority;
```suggestion
var int RightClickMeleePriority;
```

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +/// on an enemy unit.  This upgrades the logic for that selection process to now
```suggestion
/// on an enemy unit. This upgrades the logic for that selection process to now
```

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +/// EndOfMoveTrigger = new class'X2AbilityTrigger_EndOfMove';
```suggestion
/// local X2AbilityTrigger_EndOfMove EndOfMoveTrigger;
///
/// EndOfMoveTrigger = new class'X2AbilityTrigger_EndOfMove';
```

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +/// ```
```suggestion
/// ```unrealscript
```

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +static function X2AbilityTrigger_EndOfMove GetEndOfMoveTrigger(X2AbilityTemplate Template)
```suggestion
static private function X2AbilityTrigger_EndOfMove GetEndOfMoveTrigger(X2AbilityTemplate Template)
```

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +			return X2AbilityTrigger_EndOfMove(Trigger);
Please avoid doing the same cast twice

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +	CurrentPriority = 2147483647; // Max INT
Both of these are useless:

> ```uc
> PriorityAbility = none;
> ```

That's the default value of object variables anyway

> ```uc
> CurrentPriority = 2147483647; // Max INT
> ```

Never relevant due to `if(PriorityAbility == none`

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +	local int CurrentPriority, AbilityPriority;
Please comment out base game variables (which are no longer used) and add a separate `// Variables for Issue #1138` block

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +			AbilityPriority += Action.ShotHUDPriority;
This is not a secondary sort, this is a modifier to primary sort

2022-02-27 10:22 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +			AbilityPriority = EndOfMoveTrigger.RClickMeleePriority >= 0 ? EndOfMoveTrigger.RClickMeleePriority : const.SHOT_HUD_PRIORITY;
Several questions:

1) Why `SHOT_HUD_PRIORITY` was chosen as the name for default right-click-melee priority? Seems confusing/misleading to me
2) Why are negative custom explicit priorities not supported? e.g. in Nonlethal Combat case, wouldn't it make sense to set Subdue to something negative (very low) so that any other melee ability trumps it?

2022-02-27 18:23 UTC, FearTheBunnies commented
> Several overall questions:
> 
> 1. What happens if same ability has multiple `X2AbilityTrigger_EndOfMove` triggers?
> 2. What happens if the different dashing melee abilities have different target conditions? E.g. pretty sure I saw dashing medkit somewhere - but the current code doesn't support checking the (potential) target

1) I am going to address this directly, and loop through to find the highest priority option available.  It will make patching less intrusive for mod makers (not accounting for conflicting patching).  In theory there should only ever be 1 on a skill, but if a mod adds a second one because they want a higher priority for that specific skill they can.
2) That scenario is handled by 
```
	// Is the action even available?
	if(Action.AvailableCode != 'AA_Success')
	{
		continue;
	}
```
That will filter down to the correct movement skill based upon targets, etc.

2022-02-27 18:26 UTC, FearTheBunnies commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +			AbilityPriority = EndOfMoveTrigger.RClickMeleePriority >= 0 ? EndOfMoveTrigger.RClickMeleePriority : const.SHOT_HUD_PRIORITY;
Negative values are not supported because it is mirroring the ShotHUDPriority scale, meaning that 0 will be the highest priority due to wanting the "left-most" skill in the Shot HUD.  I have tweaked the comments and naming conventions to make this clearer.

2022-03-02 08:33 UTC, Xymanek commented
Better compare: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/compare/0cb9ce172246e7197cbb6c2d2dcdbdb6d8892d8a...aa8d059bee77d4b8d8565e49ec6f99004ebe7635

2022-03-02 23:51 UTC, FearTheBunnies commented
Flattened the commits to have a distinct add commit and a distinct edit commit

2022-07-28 21:20 UTC, Iridar commented
Per Discord discussion, I propose using a DLC hook for this, with the following algorithm:

1. `GetAvailableEndOfMoveAbilityForUnit()` gathers Ability States of abilities eligible for end-of-move activation (by checking trigger on the template)
2. (optional / pending discussion) Sorts the array of Ability States by Shot HUD Priority.
3. Runs the DLC hook, passing it the Unit State and `out array` of Ability States.
4. DLC hooks in mods, if any, apply their own arbitrary sorting logic to the array.
5. `GetAvailableEndOfMoveAbilityForUnit()` chooses whichever Ability State is in the 0th index of the array.

Would also need to handle the case if a mod decides to wipe the array entirely. I see two options:
1. Store the 0th Ability State before passing the array to the hook, and then use that Ability State if the array returns empty, so we can activate _something_.
2. Forbid using End of Move melee at all in those conditions, assuming the array was wiped with a purpose.

2022-07-29 18:01 UTC, FearTheBunnies commented
Closing this pull request because better approach is in a different branch.

2022-07-29 18:01 UTC, closed without merging