Allow mods to Override Rolling for negative traits
X2CommunityCore/X2WOTCCommunityHighlander pull request #1151
Opened 2022-06-30 16:06 UTC by Grobobobo

2022-06-30 16:09 UTC, Grobobobo commented
Fixes #1150 .

2022-06-30 19:22 UTC, Grobobobo commented
Should be fine now

2022-07-04 07:55 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	local bool ShouldAcquireTrait;
```suggestion
	local bool ShouldAcquireTrait; // Variable for issue #1150
```

2022-07-04 07:55 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	if(OverrideNegativeTraitRoll(ShouldAcquireTrait, NewGameState))
The current code is a bit confusing to read (one would expect `if (OverrideNegativeTraitRoll())` then skip vanilla logic), so I suggest the following refactor:

```uc
// Start Issue #1150
// Roll to see if they should gain a trait
ShouldAcquireTrait = CanAcquireTrait(false) && RollValue < (WillPercentMark + HealthPercentMark); // Vanilla logic
ShouldAcquireTrait = OverrideNegativeTraitRoll(ShouldAcquireTrait, NewGameState);

if (ShouldAcquireTrait)
// End Issue #1150
{
```

2022-07-04 07:55 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	XComGameState NewGameState)
Put this function right after `RollForNegativeTrait` (where it's called from)

2022-09-24 09:11 UTC, Xymanek requested changes
Please fix the comment omission and then approved

2022-09-24 09:11 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	if(ShouldAcquireTrait)
Missing `// End Issue #1150` (line after the `if`)

2023-05-11 10:45 UTC, Iridar commented
LGTM. I tested the code in-game and it works, although seems to be somewhat limited in scope, meaning that it won't allow mods to make soldiers roll for negative traits after any mission under arbitrary conditions. 

The unit must have `if(UnitState.GetMentalState() == eMentalState_Tired || UnitState.GetMentalState() == eMentalState_Shaken)` before the `XComGameStateContext_StrategyGameRule::UpdateSoldierWill()` will call `XCGS_Unit::RollForNegativeTrait()`, where the override event is triggered.

2023-05-11 10:45 UTC, Iridar approved these changes

2023-05-21 07:41 UTC, merged