Rclick melee delegate 1138
X2CommunityCore/X2WOTCCommunityHighlander pull request #1152
Opened 2022-07-29 18:04 UTC by FearTheBunnies

Uses a delegate based approach to expanding the functionality versus actually forcing a revised sorting algorithm.  Will allow other mods to hook into the right-click  melee determination logic and provide prioritization dynamically for which melee ability should be used.

2023-05-11 09:34 UTC, Iridar requested changes
Either way this would be a useful functionality to have, so I hope you can address the requested changes so this can be added to CHL.

2023-05-11 09:34 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +		if(PrioritizedMeleeAbility == none)
This logic seems weird to me. So you set

`PrioritizedMeleeAbility = FirstMeleeAbility;`

Then run the override delegates, and then you do

`if(PrioritizedMeleeAbility == none)`

but this will be true only if one of the delegates has explicitly set `PrioritizedMeleeAbility = none`, and otherwise it will remain equal to `FirstMeleeAbility`.

It just feels weird. Could you perhaps rewrite the logic to be more consistent?

2023-05-11 09:34 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +var int RightClickMeleePriority;
You've added this value, but it doesn't seem to get used anywhere?

2023-05-11 09:34 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +		CHHelpersObj.TriggerPrioritizeRightClickMelee(MeleeAbilities, PrioritizedMeleeAbility);
You should send as much info as possible with the delegate trigger, specifically the source Unit State. There could be value in sending the  `AvailableAction` too (the `AvailableActions[ActionIndex]`). 

Though I suppose the delegates could get the Unit State from History using the `AbilityState.OwnerStateObject`, but I still think it's worth sending it as is.

There could also be value in moving the whole override code to the place in code where the mods will be able to override which right click ability is used based on the specific target.

2023-05-11 14:11 UTC, FearTheBunnies commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +var int RightClickMeleePriority;
That value is meant to be used by partner mods to this delegate.  For example, this is the priority calculation from my companion mod:

`// Calculate priority
// If default value then use STANDARD_PRIORITY_MELEE, otherwise grab its priority
AbilityPriority = EndOfMoveTrigger.RightClickMeleePriority;
if(AbilityPriority == 0)
{
	AbilityPriority = const.STANDARD_PRIORITY_MELEE;
}
else if (AbilityPriority < 0)
{
	// We're using SHOT_HUD approach, so treat negative values as extremely high positive values
	AbilityPriority = (AbilityPriority * -1) + const.STANDARD_PRIORITY_MELEE + const.STANDARD_PRIORITY_MELEE;
}`

2023-05-12 06:57 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +var int RightClickMeleePriority;
That seems a bit situational. I don't think that's reason enough to add a new variable with unclear purpose into Highlander's code. You can always have a specific priority associated with a specific ability in your own mod, you don't need Highlander to store that information for you.

2023-05-15 21:34 UTC, FearTheBunnies commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +		CHHelpersObj.TriggerPrioritizeRightClickMelee(MeleeAbilities, PrioritizedMeleeAbility);
I tried to pass either GameRulesCache_Unit or array<AvailableActions> to the delegate, but for whatever reason CHHelpers threw an unknown type compilation error when I tried to use those as parameter types in the delegate. So instead I updated the documentation snippet to include the code needed to load the cache from the history so that folks can do what they want with it.

2023-05-15 21:36 UTC, FearTheBunnies commented
Simplified the process significantly by reducing a lot of the clunkiness and now passes UnitState to the delegate allowing for the end consumer to interact with it and the ruleset cache as much as the desire.  Should be much cleaner now.

2023-05-21 07:32 UTC, Iridar requested changes
> Simplified the process significantly by reducing a lot of the clunkiness and now passes UnitState to the delegate allowing for the end consumer to interact with it and the ruleset cache as much as the desire. Should be much cleaner now.

It seems alright superficially, I haven't gone through it letter by letter or ran any tests yet. I still think the system would benefit from being able to override which ability to use depending on the target.

This would just mean copying the code from the `X2AbilityTrigger_EndOfMove` to:

 **1) [XComTacticalInput](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/73240bdf7b1b19d009a3962614ae3aa29969ea81/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalInput.uc#L3116)** - here you would have to retrieve the target State Object from History using `PathingPawn.LastTargetObject.GetReference().ObjectID`.

**2) [XComPathingPawn](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/73240bdf7b1b19d009a3962614ae3aa29969ea81/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComPathingPawn.uc#L515)** - you get `XComGameState_BaseObject TargetObject` right in the function arguments.

The `X2AbilityTrigger_EndOfMove` should still call the override though, just without the target state. You can make the target state object an optional argument for the delegate, or just explicitly pass `none` there. 

This is just so that the override can remain at least somewhat functional in case mod-added code also runs `X2AbilityTrigger_EndOfMove::GetAvailableEndOfMoveAbilityForUnit()`.

2023-05-26 20:52 UTC, FearTheBunnies commented
Updated to include the target object now.  Still tried to maintain a minimal footprint in the Highlander itself.

2023-08-14 10:55 UTC, Iridar requested changes

2023-08-14 10:55 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +///     if(`TACTICALRULES.GetGameRulesCache_Unit(UnitState.GetReference(), UnitCache))
Arguably shouldn't be here, leave it to individual mods to figure out how they want to find the Ability State they want to use.

2023-08-14 13:03 UTC, FearTheBunnies commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +///     if(`TACTICALRULES.GetGameRulesCache_Unit(UnitState.GetReference(), UnitCache))
*shrug* Fair enough. Only added it to be nice to folks consuming this.

2023-08-14 13:29 UTC, FearTheBunnies commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTrigger_EndOfMove.uc
> +	return GetAvailableEndOfMoveAbilityForUnitWithTarget(UnitState, none);
I tweaked the implementation a little by finally realizing there are actually two things at play here. First thing is allowing a mod to fix the "bug" of the right-click priority choosing abilities that are non-intuitive.  The second thing was enhancing the selection ability to allow for the target to be provided increasing the flexibility of the choice.

2023-08-15 17:58 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +///```
Discord formatting?

2023-08-15 18:20 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +///```
HL-Docs can render UC code in a similar fashion, example: [this](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/master/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2BodyPartTemplateManager.uc#L65-L117) -> [renders like this](https://x2communitycore.github.io/X2WOTCCommunityHighlander/misc/BodyPartTemplateNames/)

2023-08-19 07:42 UTC, Iridar commented
Moved the override trigger after the default logic so that the override could allow for a more informed decision without directly replicating base game logic.

2023-08-19 07:43 UTC, Iridar commented
This is tested and ready to go, just waiting for @FearTheBunnies to squash the commit with my adjustments and it'll be ready to merge.

2023-08-19 16:24 UTC, merged