Event for EvaluateTacticalMusicState #1153
X2CommunityCore/X2WOTCCommunityHighlander pull request #1154
Opened 2022-09-21 02:46 UTC by FearTheBunnies

This adds XComTacticatalMusicStateManager and an event for overriding local player state.  Closes #1153 .

2022-09-24 16:12 UTC, Xymanek commented
Review pending until discussion on discord on possible other approaches is resolved

2023-05-11 06:02 UTC, Iridar requested changes

2023-05-11 06:02 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalSoundManager.uc
> +	`XEVENTMGR.TriggerEvent('FinalizePlayerStateForTacticalMusic', Tuple, self, none);
The current Highlander policy regarding override events is to have them in a separate `private` function. [For example.](https://github.com/long-war-2/X2WOTCCommunityHighlander/blob/b35a07f90f5786b517941026fc6005744adc31e1/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc#L1120) So please do that. 

Also, since the Player State object is the only piece of data in the Tuple, you could probably just send it as `EventData`, unless there's a possibility more stuff will be added to the Tuple in the future.

2023-05-21 07:15 UTC, Iridar requested changes

2023-05-21 07:15 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalSoundManager.uc
> +/// There is one event:
> there is one event which will allow for finalizing the active player information.

I'd phrase that as "the `'FinalizePlayerStateForTacticalMusic'` event allows mods to override the Player State or its parameters"

> There is one event:

This line probably doesn't need to be here.

2023-05-21 07:15 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalSoundManager.uc
> +/// EventData: [inout XComGameState_Player LocalPlayerState],
The `[ ]` brackets are used to format an XComLWTuple, which you're not using here. The event information must be formatted properly, because it will be used to generate example event listener functions, such as the one provided **[here](https://x2communitycore.github.io/X2WOTCCommunityHighlander/tactical/OverrideUnitFocusUI/#overrideunitfocusui)**.

So the `EventData: [inout XComGameState_Player LocalPlayerState],` line must be changed to `EventData: XComGameState_Player (LocalPlayerState),`

2023-05-29 23:56 UTC, Iridar approved these changes
Looks good. Have you tested this to confirm this event actually works for your use case?

2023-08-12 02:27 UTC, Iridar commented
Per linked steam discussion, this can be useful to someone.

2023-08-12 02:27 UTC, merged