Override patrol destinations
X2CommunityCore/X2WOTCCommunityHighlander pull request #1168
Opened 2023-04-27 00:20 UTC by RedDoby

#718 
Allow mods to override patrol locations from other alert data causes. Listeners can set `AllowThisCause` to `true` to allow this AlertCause to be used as a patrol destination for this AI group.

2023-05-11 05:52 UTC, Iridar requested changes

2023-05-11 05:52 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIPatrolGroup.uc
> +			OverrideTuple = new class'XComLWTuple';
The code you have now will probably work and be sufficient for your purpose, but there's a number of ways it can be improved.

1. The current Highlander policy regarding override events and Tuples is to form the Tuple and trigger the event in a separate private function, **[for example](https://github.com/long-war-2/X2WOTCCommunityHighlander/blob/b35a07f90f5786b517941026fc6005744adc31e1/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc#L1120)**.

2. Your override event allows considering more alert causes, but it doesn't allow to *not* consider certain alert causes. I know nothing about AI and the alert system, so I'm not sure how much value would be in that, but allowing it wouldn't take anything away from you want to do, so there's no reason not to do it. Normally it would be done like this:

```
OverrideTuple.Data[1].Kind = XComLWTVBool;
OverrideTuple.Data[1].b = AlertData.AlertCause == eAC_ThrottlingBeacon || AlertData.AlertCause == eAC_MapwideAlert_Hostile || AlertData.AlertCause == eAC_MapwideAlert_Peaceful;

TriggerEvent

return OverrideTuple.Data[1].b;
```

3. You could probably send more information with the event, such as using the `XComGameState_AIUnitData AIData` as `EventSource`. Again, no idea how much value is in that.
4. There could be value in allowing to override the `CurrDestination` with the event as well. You could do 
```
CurrDestination = `XWORLD.GetPositionFromTileCoordinates(AlertData.AlertLocation);
```
before you trigger the override the event, then send the value of the `CurrDestination` in the Tuple, and then take it back from the Tuple. 

Addressing the (1) is mandatory, so please do that, as for the other stuff, they're just suggestions, other people who know more about AI / alerts are welcome to weigh in on that.

2023-08-16 17:36 UTC, RedDoby commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIPatrolGroup.uc
> +			OverrideTuple = new class'XComLWTuple';
Thanks for the suggestions, I opted to go with the basic changes. This is just eliminating an MCO and I don't see anyone else using this.

2023-08-16 23:14 UTC, Iridar commented
That's a bit disappointing, because right the event seems of very limited use and does not seem to do what its name suggests it does. I.e. you don't get to override the destination, you're overriding whether a particular alert cause is considered. At least that's how it looks to me. But alright, if that's what you need.

Just one final request at this point: please squash the two last commits, so that are only two commits in this PR, the first one where you add the new file to source, and second where you add the event itself, and I'll merge this.

2023-08-17 01:13 UTC, RedDoby commented
> That's a bit disappointing, because right the event seems of very limited use and does not seem to do what its name suggests it does. I.e. you don't get to override the destination, you're overriding whether a particular alert cause is considered. At least that's how it looks to me. But alright, if that's what you need.
> 
> Just one final request at this point: please squash the two last commits, so that are only two commits in this PR, the first one where you add the new file to source, and second where you add the event itself, and I'll merge this.

Done

2023-08-17 01:21 UTC, Iridar commented
Uhh still seeing three commits in this PR

2023-08-17 03:08 UTC, RedDoby commented
> Uhh still seeing three commits in this PR

Now I have 6 commits. I am not sure what is happening or how to fix this. SIgh..

2023-08-17 03:30 UTC, Iridar commented
> > Uhh still seeing three commits in this PR
> 
> Now I have 6 commits. I am not sure what is happening or how to fix this. SIgh..

You need to do an interactive rebase and squash all commits besides the one where you add new file to source. In your case it would be:

git rebase -i HEAD~6

Then you'll need to edit a couple of documents, comments will explain. Once you're done, force push.

2023-08-17 17:39 UTC, RedDoby commented
> > > Uhh still seeing three commits in this PR
> > 
> > 
> > Now I have 6 commits. I am not sure what is happening or how to fix this. SIgh..
> 
> You need to do an interactive rebase and squash all commits besides the one where you add new file to source. In your case it would be:
> 
> git rebase -i HEAD~6
> 
> Then you'll need to edit a couple of documents, comments will explain. Once you're done, force push.

I am going around in circles trying to google how to run this command you suggested. Is it from the windows command line or is there some other tool? Maybe you can point me in the right direction.

2023-08-17 20:48 UTC, Iridar commented
> > > > Uhh still seeing three commits in this PR
> > > 
> > > 
> > > Now I have 6 commits. I am not sure what is happening or how to fix this. SIgh..
> > 
> > 
> > You need to do an interactive rebase and squash all commits besides the one where you add new file to source. In your case it would be:
> > git rebase -i HEAD~6
> > Then you'll need to edit a couple of documents, comments will explain. Once you're done, force push.
> 
> I am going around in circles trying to google how to run this command you suggested. Is it from the windows command line or is there some other tool? Maybe you can point me in the right direction.

What git client are you using?

2023-08-18 03:01 UTC, RedDoby commented
> > > > > Uhh still seeing three commits in this PR
> > > > 
> > > > 
> > > > Now I have 6 commits. I am not sure what is happening or how to fix this. SIgh..
> > > 
> > > 
> > > You need to do an interactive rebase and squash all commits besides the one where you add new file to source. In your case it would be:
> > > git rebase -i HEAD~6
> > > Then you'll need to edit a couple of documents, comments will explain. Once you're done, force push.
> > 
> > 
> > I am going around in circles trying to google how to run this command you suggested. Is it from the windows command line or is there some other tool? Maybe you can point me in the right direction.
> 
> What git client are you using?

I was using GitHub. I found git bash and gitextensions and installed them both. Now I can navigate to the local repository in GitBash but when I try and run the command you suggested it states "fatal: this operation must be run in a work tree".

2023-08-18 03:10 UTC, Iridar commented
> I was using GitHub. I found git bash and gitextensions and installed them both. Now I can navigate to the local repository in GitBash but when I try and run the command you suggested it states "fatal: this operation must be run in a work tree".

Yeah as far as I know you can't do elaborate things like squashing specific commits via github interface. I don't really know anything about git extensions or git bash, but if you ping me on Discord, I can explain how to use Source Tree, it's a standalone app with a proper graphical interface for using git.

2023-08-18 03:10 UTC, Iridar commented
Though at this point it might be easier to just squash these myself, let me try that.

2023-08-18 03:13 UTC, Iridar approved these changes

2023-08-18 03:13 UTC, merged

2023-08-18 03:20 UTC, RedDoby commented
> Though at this point it might be easier to just squash these myself, let me try that.

Sweet. Thank you.