IsIncapacitated check to GatherUnitsToMove #1193
X2CommunityCore/X2WOTCCommunityHighlander pull request #1194
Opened 2023-06-11 21:32 UTC by Tepa00

This allows the AI to skip incapacitated units in a group which has other units able to act.

2023-06-24 15:16 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIPlayer.uc
> +		if(bDead || UnitState.bRemovedFromPlay || UnitState.NumAllActionPoints() == 0 || UnitState.IsIncapacitated()) // || kBehavior == None || kBehavior.DecisionStartHistoryIndex > kAIPlayerData.m_iLastE
Are you positive that `UnitState.IsIncapacitated()` returns true only if the unit is unconscious or bleeding out?

2023-06-24 15:34 UTC, Tepa00 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIPlayer.uc
> +		if(bDead || UnitState.bRemovedFromPlay || UnitState.NumAllActionPoints() == 0 || UnitState.IsIncapacitated()) // || kBehavior == None || kBehavior.DecisionStartHistoryIndex > kAIPlayerData.m_iLastE
Yes

2023-06-24 15:45 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIPlayer.uc
> +		if(bDead || UnitState.bRemovedFromPlay || UnitState.NumAllActionPoints() == 0 || UnitState.IsIncapacitated()) // || kBehavior == None || kBehavior.DecisionStartHistoryIndex > kAIPlayerData.m_iLastE
It's not documented though. You're probably right, but I'd rather be extra careful. I think it would be better to add `UnitState.IsUnconscious()` and `UnitState.IsBleedingOut()`. Both are native functions, so the performance loss from calling two separate methods should be negligible.

2023-06-24 17:07 UTC, Tepa00 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIPlayer.uc
> +		if(bDead || UnitState.bRemovedFromPlay || UnitState.NumAllActionPoints() == 0 || UnitState.IsIncapacitated()) // || kBehavior == None || kBehavior.DecisionStartHistoryIndex > kAIPlayerData.m_iLastE
Done.

2023-06-25 09:58 UTC, Iridar requested changes
The docs still mention the `IsIncapacitated()`, please update. Also I think this should have the 

/// HL-Docs: ref:Bugfixes; issue:1193

tag.

2023-06-25 19:04 UTC, Iridar approved these changes

2023-06-25 19:09 UTC, Iridar commented
Approved, to be squash merged, ideally test first.

2023-08-10 10:35 UTC, Iridar commented
Tested, seems to be working.

2023-08-10 10:36 UTC, merged