Updated EndTacticalHealthMod() in XCGS_Unit
X2CommunityCore/X2WOTCCommunityHighlander pull request #1202
Opened 2023-06-22 22:13 UTC by BlackDog86

Added a boolean value to CHHelpers & updated code in EndTacticalHealthMod() in XCGS_Unit to allow other mods to set a config variable in XComGame.ini to disable the additional 50% health the game automatically grants to soldiers at the end of a mission when beta strike is active. 

 If the variable is false, or doesn't exist , the base game behaviour is retained.

2023-06-24 12:13 UTC, Iridar commented
If the first message in the PR has something like "Closes #1192" or "Fixes #1192", then the corresponding issue will be closed automatically when the PR is merged, so do that in the future, please. I've edited the post for you for now.

2023-06-24 15:13 UTC, Iridar requested changes

2023-06-24 15:13 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	if (LowestHP > 0 && `SecondWaveEnabled('BetaStrike') && !class'CHHelpers'.default.bDisableBetaStrikePostMissionHealing)  // Immediately Heal 1/2 Damage
Nitpicking, but I think that for the sake of clarity it would be better to put in a separate if() statement with your config variable.

2023-06-24 17:41 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +;bDisableBetaStrikePostMissionHealing=true ; Uncomment this to disable the wound reduction after a mission with Beta Strike enabled
committed

2023-06-24 17:41 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +;;; HL-Docs: ref:BetaStrikeEndTacticalHeal
committed

2023-06-24 17:41 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +// End Issue #815
fixed

2023-06-25 10:03 UTC, Iridar requested changes

2023-06-25 10:03 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +			HealthLost -= SWHeal;
Please add indentation here. Four spaces is the standard.

2023-06-25 10:03 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	//	Issue #917: Allow beta strike additional healing to be disabled by config
Again, since this is the actual code change, I think 

;;; HL-Docs: feature:BetaStrikeEndTacticalHeal; Issue #917

tag is warranted here.

2023-06-25 10:03 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; Uncomment this to disable the wound reduction after a mission with Beta Strike enabled
I would reword the comment slightly.

Something like: "With Beta Strike enabled, soldiers are normally immediately healed for 50% of their missing HP after a mission. Uncomment this to disable this behavior."

2023-07-12 07:10 UTC, BlackDog86 commented
Issues resolved - ready for review

2023-07-12 07:22 UTC, Iridar requested changes
There's still a formatting issue with HL-Docs.

A HL-Docs entry must look either like this:

`/// HL-Docs: feature:YourFeature; issue:1337;`

or like this:

`/// HL-Docs: feature:YourFeature; issue:1337; tags:tactical`

Tags are optional.
Either `///` or `;;;` are used depending on whether this is in script or in config.

Each feature must have at least one HL-Docs entry like this, where both feature name and issue number are specified.

All other HL-Docs entries should have only the feature name with the `ref` keyword:

`;;; HL-Docs: ref:YourFeature;`

All comments under HL-Docs entry that are also prefaced with `///` or `;;;` get pulled into the **[Highlander online documentation](https://x2communitycore.github.io/X2WOTCCommunityHighlander/)** automatically, where the entry with the `feature` and `issue` is used to generate the header, while all other entries with `ref` are appended to the page.

The only exception to this rule is the `ref:Bugfixes`, which looks like this:

HL-Docs: ref:Bugfixes; issue:644

And it has both a `ref` and an `issue` number.

2023-07-12 17:40 UTC, BlackDog86 commented
Please tell me it's right this time! Changed committed & pushed :)

2023-07-12 19:05 UTC, Iridar commented
> Avoid trailing semicolons in the HL-Docs lines (and you should probably lowercase issue)

(c) sempai

2023-07-13 03:44 UTC, Iridar commented
The docs builder still fails, sorry, looks like I was wrong and the `tags` keyword is mandatory.

Try it like this:

`/// HL-Docs: feature:BetaStrikeEndTacticalHeal; issue:917; tags:`

2023-07-13 18:28 UTC, BlackDog86 commented
OK last time! Please work!

2023-07-13 18:32 UTC, Iridar approved these changes

2023-07-13 18:33 UTC, Iridar commented
Praise Johnny Lump!

2023-08-10 10:49 UTC, merged