Issue #1191 - Expose GetDateString() method in X2StrategyGameRuleSetDataStructures to Config
X2CommunityCore/X2WOTCCommunityHighlander pull request #1205
Opened 2023-06-24 19:43 UTC by BlackDog86

Fixes #1191

Adds three potential config entries to XComGame.ini:
bForceEuroDateStrings (If true - Dates in format DD/MM/YYYY)
bForceISOFormatEU (If true - Dates in format YYYY/MM/DD for improved sorting behaviour - EU locales only)
bForceISOFormatRestOfWorld (If true - Dates in format YYYY/MM/DD for improved sorting - Non-EU locales)

This alters the output of GetDateString() which shows the date in various places in the game (memorial / logs etc.).  Note that this fix has no effect on the save/load screen which (inexplicably) uses completely different logic. I may look into fixing this in a future PR.

2023-06-24 20:19 UTC, Iridar commented on X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
This is going to be a problem, the change to the .x2proj file should be in the same commit where you add the new file. 

The usual workflow is: 

1. Create branch
2. Add the file via Modbuddy
3. Close Modbuddy saving changes - that will apply the changes of adding the new file to the .x2proj file. Or maybe clicking File -> Save All is enough, but I usually restart Modbuddy to be sure.
4. Commit.
5. Continue working.

2023-06-24 20:20 UTC, Iridar commented
I'm confused, why did you have to make localization changes for this?

2023-06-24 20:28 UTC, Iridar commented
I take it you didn't realize you could do

```
`XEXPAND.ExpandString("<XGParam:IntValue1/><XGParam:StrValue1/!SeparatorString/><XGParam:IntValue2/><XGParam:StrValue1/!SeparatorString/><XGParam:IntValue0/>");
```

The goal is to make the date display configurable, right? As I understand it, the order of these tags determines the order in which day/month/year are displayed.

The strings with these tags are already localized. Meaning that anyone can go into their localization files and reorder the tags as they want. This can also be done as a standalone mod that will reorder these tags for the user. 

I see zero reason to involve Highlander in this.

2023-06-25 00:12 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
OK didn't realise that - looks like probably gonna have to kill this branch altogether anyway so will take that under advisement.

2023-06-25 01:20 UTC, BlackDog86 commented
Significantly reduced codebase for this PR & kept focus to the original issue. Hopefully this is better.

2023-06-25 09:44 UTC, Iridar requested changes
Sorry for nitpicking, but everything in Highlander has to be just right.

2023-06-25 09:44 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +/// HL-Docs: feature:AddINTEuroDateOverRide; issue:1191;
Nitpicking, but just having

// Variable for Issue #1191

Would be enough. Stuff marked as HL-Docs will be rendered on the [Highlander documentation](https://x2communitycore.github.io/X2WOTCCommunityHighlander/) page, and there's no need for that in this case.

2023-06-25 09:44 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +	// issue #1191 - Add config option to force Euro date style with INT localisation
Since this is the actual code change with new logic, having a HL-Docs here would be reasonable.

2023-06-25 09:44 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; HL-Docs: feature:AddINTEuroDateOverRide; issue:1191;
Super nitpicking, but "override" is one word, so camelcase for it would be "Override", not "OverRide".

2023-06-25 09:52 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +	// issue #1191 - Add config option to force Euro date style with INT localisation
done

2023-06-25 09:53 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; HL-Docs: feature:AddINTEuroDateOverRide; issue:1191;
done

2023-06-29 02:19 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; HL-Docs: feature:AddINTEuroDateOverride; issue:1191;
HL-Docs in comments must be preceded by triple semicolon, or else they won't be picked up.

Also, since you already have an instance of HL-Docs that specifies feature and issue number, in other instances of HL-Docs you should just reference that feature name.

`/// HL-Docs: feature:AddINTEuroDateOverride; issue:1191`

So in the end you should have:

`;;; HL-Docs: ref:AddINTEuroDateOverride;`

I also recommend renaming the feature to `EuroDateOverride`, "Add" is redundant and "INT" doesn't actually have anything to do with the feature, as it's applied regardless.

2023-06-29 02:19 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		/// HL-Docs: feature:AddINTEuroDateOverride; issue:1191 - Add config option to force Euro date style with INT localisation
This should be split into two lines, the HL-Docs header and the comment itself.

2023-07-12 05:40 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; HL-Docs: feature:AddINTEuroDateOverride; issue:1191;
Update

2023-07-12 05:40 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		/// HL-Docs: feature:AddINTEuroDateOverride; issue:1191 - Add config option to force Euro date style with INT localisation
Done

2023-07-12 06:11 UTC, Iridar requested changes

2023-07-12 06:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +;;; HL-Docs: feature:EuroDateOverride;
Replace `feature` with `ref` please, only one HL-Docs entry per unique issue should have the `feature` keyword, followed by the issue number.

In other words, it's either:

/// HL-Docs: feature:EuroDateOverride; issue:1191

which can be only one, as I understand it, or:

/// HL-Docs: ref:EuroDateOverride;

2023-07-12 07:09 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +;;; HL-Docs: feature:EuroDateOverride;
Done

2023-07-12 07:52 UTC, Iridar approved these changes

2023-07-12 07:53 UTC, Iridar commented
@BlackDog86 
All good. Could you please squash the last two commits, so there are only two, one with new file, and one with the rest of the changes?

2023-07-13 18:31 UTC, BlackDog86 commented
Squashed & comments updated

2023-07-13 18:43 UTC, Iridar commented
Sorry, I haven't caught this earlier, `class'CHHelpers'.default.bForceEuroDateStrings == true` is wasteful, `class'CHHelpers'.default.bForceEuroDateStrings` is enough, it's already a bool value.

2023-07-13 19:29 UTC, Iridar approved these changes

2023-08-10 10:02 UTC, merged