Issue# 1181
X2CommunityCore/X2WOTCCommunityHighlander pull request #1208
Opened 2023-06-25 07:58 UTC by BlackDog86

Fixes #1181 

Added UIFacilityGrid_FacilityOverlay & replaced appropriate code with that from the Clearing-UI-Indicator fix.

Tested & working as expected - engineer staffed in second excavation slot appears in the second slot on the UI.

2023-06-26 22:09 UTC, BlackDog86 commented
Anything else needed on this one?

2023-06-26 22:37 UTC, Iridar requested changes

2023-06-26 22:38 UTC, Iridar commented
> Anything else needed on this one?

Apparently forgot to click the button to finish the review and my messages weren't visible to you.

2023-08-10 15:15 UTC, Iridar commented
Still has unaddressed issues since the last review.

2023-08-12 10:19 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIFacilityGrid_FacilityOverlay.uc
> +	`XEVENTMGR.TriggerEvent('FacilityUICustomizeHook', Tuple, Room);
Ah those are just hooks from the original mod to allow over-riding some facility status labels. Not important at all, will remove.

2023-08-12 10:37 UTC, BlackDog86 commented
Updated & tested. Should be ready for merge.

2023-08-12 14:51 UTC, RustyDios commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIFacilityGrid_FacilityOverlay.uc
> +	`XEVENTMGR.TriggerEvent('FacilityUICustomizeHook', Tuple, Room);
If you are integrating the mod, then surely NOT including these hooks could break any mods dependant on them from the original mod ??

2023-08-12 15:39 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIFacilityGrid_FacilityOverlay.uc
> +	`XEVENTMGR.TriggerEvent('FacilityUICustomizeHook', Tuple, Room);
We're integrating the bugfix, not the mod.

2023-08-13 08:46 UTC, Iridar approved these changes
Looks sane, gonna merge after testing.

2023-08-13 09:11 UTC, Iridar commented
Tested, works fine. Good work.

2023-08-13 09:11 UTC, merged