Implement Better Positive Trait UI
X2CommunityCore/X2WOTCCommunityHighlander pull request #1212
Opened 2023-06-26 10:06 UTC by BlackDog86

Fixes #1081 

Summary:

1. Modified UIAlert to use the "TrainingComplete" alert for positive traits - This has the same set of UI elements as Alert_NegativeSoldierEvent for negative traits but with a neutral colour scheme & promotion-icon.

2. Updated XcomHQPresentationLayer to check whether traits are positive or negative before calling the notifybanner function (this is the piece which places the trait notifications on the bottom left of the screen). Adjusted colours and icons to make more sense.

3. Adjusted the UIAvengerHUD OnClickTraitIcon function so that if someone clicks on a soldier walking around the avenger with a negative or positive trait icon (like the bond icon), it takes them to the correct UI Panel for that trait. 

Note that I can't confirm this new code actually does anything - I can't remember seeing anyone walking around with trait icons bobbing around so probably the function is never called for, but anyway, the code now includes positive traits as well in case that behaviour is ever fixed in the future.

2023-06-26 10:25 UTC, RustyDios commented
A quick glance, and I fully agree this looks like it fixes a lot of issues there are various places that have for example;
```
-var() bool							bHasSeenNegativeTraitPopup;
//Issue# 1081 - Alter bool name so it applies to both positive and negative traits
+var() bool							bHasSeenTraitPopup;
```

Which would break the CHL backwards compatibility policy on any mods previously reliant on the removed bool.
Rather than remove the word 'Negative' from everything, a better approach should be to duplicate the variables adding 'Positive' and make the code account for both.

2023-06-26 11:43 UTC, robojumper commented
`XComGameState_HeadquartersXCom` is a native class, so property additions are disallowed. Also in general, keep property names and function names and arguments the same -- even if they have "negativeTrait" in their name, simply keep that and add a comment that this does more than what the name implies.

2023-06-26 20:02 UTC, BlackDog86 commented
> A quick glance, and I fully agree this looks like it fixes a lot of issues there are various places that have for example;
> 
> ```
> -var() bool							bHasSeenNegativeTraitPopup;
> //Issue# 1081 - Alter bool name so it applies to both positive and negative traits
> +var() bool							bHasSeenTraitPopup;
> ```
> 
> Which would break the CHL backwards compatibility policy on any mods previously reliant on the removed bool. Rather than remove the word 'Negative' from everything, a better approach should be to duplicate the variables adding 'Positive' and make the code account for both.

BC did cross my mind when I changed that - I don't think it matters to just change it back and comment that the function does 'more than what it says on the tin' as it were

2023-07-01 08:32 UTC, BlackDog86 commented
Requested changes now implemented (no changes to XComGameState_HeadquartersXCom and function names kept the same for BC)

2023-07-01 08:37 UTC, Iridar requested changes

2023-07-01 08:37 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAlert.uc
> +simulated function BuildNegativeTraitAcquiredAlert(bool bPositiveTrait)
Without looking at anything else, you can't change function definitions of existing functions, that breaks the BC.

The only exception are private/final internal Highlander functions that are explicitly not covered by the BC policy.

2023-07-01 10:40 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAlert.uc
> +simulated function BuildNegativeTraitAcquiredAlert(bool bPositiveTrait)
Understood - I've now reworked the code so that all base game functions are left unmodified.

2024-05-31 12:23 UTC, BlackDog86 commented
Are there any more changes required on this or is it just a timing thing?

2024-11-11 11:05 UTC, Iridar reviewed
To be clear, this feature adds just a UI, right? But no way for units to actually acquire positive traits? Docs need to specify how mod authors should take advantage of this feature.

2024-11-11 11:05 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAlert.uc
> +	LibraryPanel.MC.BeginFunctionOp("UpdateData");1
What is this stray `1` at the end of the line? Would this even compile?

2024-11-11 13:49 UTC, BlackDog86 commented
> To be clear, this feature adds just a UI, right? But no way for units to actually acquire positive traits? Docs need to specify how mod authors should take advantage of this feature.
> 
> And I'd love to see some screenshots of this UI in action from an example use case.

There are pictures of the updated UI in Issue #1081 - not sure how that 1 got in there either - it's probably a stray key-press from when I was fixing commits that had gotten a long way behind the master earlier this month.

2024-11-11 19:15 UTC, BlackDog86 commented
Additionally, the base game only allows for one trait popup message to appear at a time. Personally I'd prefer if each trait brought its own popup message when its triggered but I didn't think that that was enough of a justification to comment out the block below. Also, if you use the 'starting traits' mod, it does mean it could bring up quite a few popups when you start a new campaign but I'm open to discussion on leaving the base game code as it is, or adjusting it.

```
> if(PopupCount > 0 && !XComHQ.bHasSeenNegativeTraitPopup)
> 				{
> 					XComHQ.bHasSeenNegativeTraitPopup = true;
> 					UINegativeTraitAlert(NewGameState, PopupUnit, StoredTraitName);
> 				}
```

2024-11-16 04:53 UTC, Iridar requested changes
Looks mostly okay to me, but I have issues with it being a bit messy, like fixing typos or adding random empty spaces to lines.

I'm also nitpicking to docs. 

The point of HL-Docs in this case is to be mod author facing, so they can get a clean and concise explanation of what this CHL feature can do for them.

Something along the lines of:

_"Positive traits are a scrapped WOTC feature, on release the game had only negative traits, so there is no UI for "positive trait acquired", but X2TraitTemplate does have a `bPositiveTrait` flag. This feature repurposes "soldier promoted" UI to make it function as a makeshift "positive trait acquired UI". To make the game display it when the soldier acquires a positive trait, simply set bPositiveTrait = true; on your X2TraitTemplate."_

This all can be done as one piece of Docs somewhere, and the rest of the changes can be marked with standard non-Docs Start/End Issue tags.

2024-11-16 04:53 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAvengerHud_SoldierStatusIndicatorContainer.uc
> -	local int UntiID;
I appreciate the diligence, but fixing typos in vanilla code is outside the scope of this PR.

2024-11-16 04:53 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
> +	if (TraitTemplate.bPositiveTrait)
Add a none-check for the trait template pls.

2024-11-16 17:06 UTC, BlackDog86 commented
OK hopefully this is a bit better.

2024-11-17 13:11 UTC, Iridar reviewed
Better, but needs work still.

2024-11-17 13:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAlert.uc
> +// Begin Issue# 1081
Misplaced space, also while "begin" is used in some CHL comments, the convention is "Start".

2024-11-17 13:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAlert.uc
> +	/// However, X2TraitTemplate does have a bPositiveTrait flag. This feature repurposes the "soldier promoted" UI to make it function as a makeshift
Feels like something is missing after the word "makeshift"?

2024-11-17 13:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAvengerHud_SoldierStatusIndicatorContainer.uc
> +	/// Issue #1081: Removed code which early exits the function if the user clicks on a positive trait
In this case it would be preferable to comment out the original code rather than removing it.

2024-11-17 13:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +// Single line for Issue #1081 - Note, this bool now also covers positive traits
Since there's no actual changes here, I suggest making it an inline comment instead.

`var() bool bHasSeenNegativeTraitPopup; // Issue #1081 - this bool now also covers positive traits`

2024-11-17 13:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
> +			// Begin Issue# 1081
Misplaced space, Begin -> Start

2024-11-17 13:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
> +					XComHQ.bHasSeenNegativeTraitPopup = true;
I'm a bit unclear, what is the purpose of this bool? Does this mean the player can see only one "negative trait acquired" popup per campaign? And what's the reasoning in making displaying a positive trait apply to it as well?

2024-11-19 12:25 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
> +					XComHQ.bHasSeenNegativeTraitPopup = true;
OK so the way this bit works is, if multiple soldiers happen to get traits on a mission (or at the start of the game, if using the 'starting traits' mod), the UI displays the popup message like this only for the first one:
![137698942-b2587684-60ad-4c30-bb3a-4063cc3d2c39](https://github.com/user-attachments/assets/895d45e7-00cd-45de-91d9-0f7a0d8e5659)
Then, any of the rest are just displayed on the LHS sidebar:
![137698952-4b71c90b-b167-46ec-8e09-3a3ea674dffd](https://github.com/user-attachments/assets/a4d3de94-6103-4c05-b35a-9d67d40f0cd2)

Personally I think the experience would be better if that bool was never set so that the trait popups display sequentially for each trait gained, rather than just once but it's a bit of a subjective change - for example, if a mod was made that gave traits to every soldier at the start of the campaign, then you could conceivably get 20 popups or something. We could set a limit of 6, which would allow displaying traits for every member of the squad on a mission but would prevent general UI spam in the event that something adds lots of traits at once.

2024-11-20 07:20 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
> +					XComHQ.bHasSeenNegativeTraitPopup = true;
Yeah I have no issues with that approach, I'm not sure why Firaxis even put that functionality in place. Though conventional CHL practice would be to gate the change behind a config bool flag, and keep things as they were by default.

2024-11-21 09:28 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
> +					XComHQ.bHasSeenNegativeTraitPopup = true;
Sorry, yes, push the new version with "allow multiple trait acquired popups" bool, defaulted to false.

2024-11-21 20:04 UTC, BlackDog86 commented
This should do the trick :)

2024-11-27 13:57 UTC, BlackDog86 commented
The comments look fine - I'll change the name of the bool value tonight. Thanks for the review.

2024-11-27 22:31 UTC, merged