Integrate Revival Protocol Fixes in CHL
X2CommunityCore/X2WOTCCommunityHighlander pull request #1237
Opened 2023-08-12 11:42 UTC by BlackDog86

Fixes #1235 - Adds a new X2Condition to the RestoreActionPoints effect to prevent it restoring APs to disoriented units. Updated the effect removal so that it can target stunned units and remove stunned status (as the base-game localization suggests) & allowed the ability to target resistance soldiers, per RMs mod - discussion could be had over whether this part should be implemented.

2023-10-29 10:58 UTC, Iridar requested changes
All Highlander submissions must be marked by comments with the issue number. 

For single line changes:

`SomeCodehere; // Single line for Issue #000`

For multiple lines:

```
// Start Issue #000
some code
blah blah code
way more code
// End Issue #000
```

2024-09-05 12:45 UTC, Iridar requested changes

2024-09-05 12:45 UTC, Iridar commented on X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Changes to .x2proj file must be in the same commit where the new files are added to the repo.

2024-09-05 12:45 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_RevivalProtocolAP.uc
> +	TargetUnit = XComGameState_Unit(kTarget);
Missing a none-check for the TargetUnit.

2024-09-05 12:45 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_RevivalProtocolAP.uc
>  	if (SourceUnit == none || TargetUnit == none)
This none check for unit states is too late.

2024-09-05 12:45 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_RevivalProtocolAP.uc
> +	if (!SourceTeam.IsEnemyPlayer(TargetTeam))
Just do `SourceUnit.IsEnemyUnit(TargetUnit);` instead.

2024-09-06 03:44 UTC, BlackDog86 commented
Changes made

2024-09-12 03:18 UTC, Iridar requested changes

2024-09-12 03:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_RevivalProtocolAP.uc
> +event name CallMeetsConditionWithSource(XComGameState_BaseObject kTarget, XComGameState_BaseObject kSource)
On second look, this whole bit is unnecessary. The `X2Condition_RevivalProtocol` on the ability template already ensures the ability can target only friendly units. This optimized version of `CallMeetsConditionWithSource()` should be moved there instead.

2024-09-12 03:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_RevivalProtocolAP.uc
> +event name CallMeetsConditionWithSource(XComGameState_BaseObject kTarget, XComGameState_BaseObject kSource)
Also I'm afraid that with current conditions if the unit is both stunned and panicked, they're gonna get a double amount of AP, needs testing.

2024-09-12 03:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_SpecialistAbilitySet.uc
> +	/// Restore APs on the unit only if the new X2Condition is met
Would be more useful if the comment gave a brief summary of what the condition checks for.

2024-10-28 22:21 UTC, closed without merging