Add config option to disable Civilians Yelling before they move
X2CommunityCore/X2WOTCCommunityHighlander pull request #1243
Opened 2023-08-17 01:00 UTC by Tedster59

Fixes #717 

This will help mods that adjust AI behavior.  Will allow Yellow Alert 2.0 (and soon LWoTC) to remove an MCO of `XGAIBehavior_Civilian`

2023-08-17 01:22 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; bDisableCivilianPreMoveYell = true
It's not a big deal, but in the future please try to maintain an empty line at the end of all files.

2023-08-17 02:49 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; bDisableCivilianPreMoveYell = true
Added

2023-08-17 03:35 UTC, Iridar requested changes

2023-08-17 03:35 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIBehavior_Civilian.uc
> +		if(!class'CHHelpers'.bDisableCivilianPreMoveYell)
This needs to be `class'CHHelpers'.default.bDisableCivilianPreMoveYell`. Please at least compile test all your Highlander submissions.

2023-08-17 03:45 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIBehavior_Civilian.uc
> +		if(!class'CHHelpers'.bDisableCivilianPreMoveYell)
Ok, fixed that boneheaded mistake

2023-08-19 04:49 UTC, Iridar commented
There was an .x2proj conflict, I tried resolving it via GitHub interface and it just FUBAR'ed the entire PR and I don't how to unfox it. Sorry, but I'm really not in the mod for git bullshit, so I'll just recreate the PR.

2023-08-19 04:49 UTC, closed without merging