skip triggering DrawDebugLabels during game state building
X2CommunityCore/X2WOTCCommunityHighlander pull request #1248
Opened 2023-08-20 11:22 UTC by remcoros

fixes #1245

As noted in the original issue, this makes it so that there is a slight delay (~ 20 frames in my profiles) during which no DrawDebugLabels events are triggered, and thus, mods using it temporarily don't draw debug labels.

I did a test using LWOTC with 'LWDebugPodJobs' console command toggled on. But the effect is not really noticeable, since it quickly catches up (~300 ms. later, and that is with the profiler ON).

Personally, I don't think we need an additional config switch to fix this and always draw.

2023-08-20 11:24 UTC, remcoros commented
Another solution would be to gate the TriggerEvent behind a config switch, and just NEVER call it if it is false. So that when the game is idling, we also do not trigger this event.

Thoughts?

2023-08-20 11:26 UTC, Iridar commented
What's the performance cost of triggering the event when it's gated behind ``XCOMGAME.GameRuleset.BuildingLatentGameState` check? If it's at least slightly significant even by a huge stretch, I suggest locking it behind a config bool.

Sidenote, ``GAMERULES.BuildingLatentGameState` should be ever so slightly.

2023-08-20 11:33 UTC, remcoros commented
The 'cost' of triggering it (during an idle frame) is near zero (depending on what mods are listening):

![image](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/assets/130373/1e88a558-d69f-4a73-80d4-2b0e6638a4da)

Checking for a config switch or BuildingLatentGameState is exactly the same (it's just checking a var).

So it's more a matter of if this event should always be triggered every frame, even for "regular players". Or gate it behind a config switch and instruct mod devs to enable this config (which will be a slight backward incompatible change).

With the config switch, we could still check BuildingLatentGameState to avoid some lag for mod devs.

2023-08-20 11:36 UTC, Iridar commented
> With the config switch, we could still check BuildingLatentGameState to avoid some lag for mod devs.

Personally I'd prefer doing it this way, because it's gonna be a waste of processing for 99.999999999% CHL mod users out there. Though like I mentioned on discord, if it were up to me, I'd gate every piece of logic that's only useful for debugging behind `final release` check.

2023-08-20 11:52 UTC, remcoros commented
Added the config option. I think that's a good compromise, this doesn't force mod devs to compile a custom CHL in non-final-release.

2023-08-28 07:27 UTC, Iridar requested changes
Other than the docs nitpick, this is good to go.

2023-08-28 07:27 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalController.uc
> +		/// HL-Docs: feature:DrawDebugLabels; issue:1245; tags:tactical
Please add a `// Start Issue #1245` above this line.

Also, this arguably doesn't require a HL-Docs entry. The only contributor value in having one is the mention of not triggering events during latent game state building, which is not exactly relevant to drawing debug labels itself. 

IMO mark this as `ref:Bugfixes`, cuz arguably the performance degradation is a bug.

2023-08-30 11:03 UTC, remcoros commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalController.uc
> +		/// HL-Docs: feature:DrawDebugLabels; issue:1245; tags:tactical
The "HL-Docs: feature DrawDebugLabels" is related to the ini setting in XComGame.ini (;;; HL-Docs: ref:DrawDebugLabels' ). I copied the pattern used for bDisableCivilianPreMoveYell.

I can change it to ref:BugFixes here, but what should the new entry in XComGame.ini then have?

2023-08-30 11:47 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalController.uc
> +		/// HL-Docs: feature:DrawDebugLabels; issue:1245; tags:tactical
Just a standard comment with the issue number would be enough, in my opinion. Alternatively, if Draw Debug Labels feature itself has a HL-Docs entry, you can add that one instead.

2023-08-30 11:58 UTC, remcoros commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalController.uc
> +		/// HL-Docs: feature:DrawDebugLabels; issue:1245; tags:tactical
I'll have a look. Ideally, anyone looking at the docs for 'DrawDebugLabels' should see that there is an ini option to be enabled before it will work.

2023-08-30 16:47 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +// Variable added Issue #1245 - enables the triggering of the DrawDebugLabels CHL event
Missed "for" here, though I'd prefer just:

// Variable for Issue ...

2023-09-17 19:41 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +; bDrawDebugLabels = true
Minor nitpick, in the future please try to always leave an empty line at the end of each file, it makes diffs cleaner.

2023-09-17 19:43 UTC, Iridar commented
This is good to go and should be squash merged.

2023-09-18 10:11 UTC, merged