Updated Lure status effect so it ticks properly & isn't removed when the source unit dies
X2CommunityCore/X2WOTCCommunityHighlander pull request #1294
Opened 2023-12-19 15:11 UTC by BlackDog86

Fixes #1286

2023-12-19 15:14 UTC, BlackDog86 commented
![image](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/assets/122568778/1fa5de19-a79c-4c05-b621-df694bcb71c9)
![image](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/assets/122568778/1f5b218d-ccfd-465b-9d8f-15ced6588d89)

Tested and now ticks properly - this issue actually only affects a couple of niche circumstances because the base game includes the ability as a passive (not a debuff) - the "Lost Lure Status Icon" mod changes this to a penalty so the tick then displayed in YAF1 (hence is invisible normally).

2024-02-27 03:52 UTC, Iridar requested changes

2024-02-27 03:52 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StatusEffects.uc
> +	UltrasonicLureTargetEffect.BuildPersistentEffect(default.ULTRASONICLURE_TURNS,false,false,,eGameRule_PlayerTurnBegin); //Issue #1286 - Keep effect when source dies, tick on turn begin. Adjust icon a
Please use Start Issue and End Issue tags when changes span multiple lines, and please add a HL-Docs ref:bugfixes entry.

2024-02-27 19:36 UTC, BlackDog86 commented
Docs tags updated

2024-02-27 20:23 UTC, Iridar approved these changes

2024-02-27 20:24 UTC, merged