Implement new override event for starting region eligibility hook
X2CommunityCore/X2WOTCCommunityHighlander pull request #1304
Opened 2024-02-24 21:57 UTC by Tedster59

Fixes issue #1303 using option #1 of an override event to allow mods to override the behavior of this function.

2024-02-25 01:24 UTC, Iridar requested changes

2024-02-25 01:24 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +/// HL-Docs: feature:OverrideElligibleStartingRegion; issue:1303; tags:strategy
Nitpicking, but `eligible` has one `l` in it.

2024-02-25 01:24 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +
Nitpicking, but this empty line isn't necessary.

2024-02-25 01:24 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +// **NOTE** This function is public so that it can be called from `XComGameState_WorldRegion`.
You can still make it `final`.

2024-02-25 01:33 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +// **NOTE** This function is public so that it can be called from `XComGameState_WorldRegion`.
done

2024-02-25 03:36 UTC, Iridar requested changes

2024-02-25 03:36 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +static final function bool IsEligibleStartRegion(XComGameState StartState, XComGameState_WorldRegion RegionState)
Sorry, I wasn't clear enough. You can't change the function definition of a function that already exists, especially one that's not a private Highlander API. I meant making the `TriggerOverrideEligibleStartingRegion()` final.

2024-02-25 03:36 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +//
Missing a third `/`? Or just remove the line.

2024-02-25 03:56 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +//
Removed

2024-02-25 03:57 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +static final function bool IsEligibleStartRegion(XComGameState StartState, XComGameState_WorldRegion RegionState)
Fixed

2024-02-25 04:15 UTC, Iridar approved these changes

2024-02-25 04:17 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +	XComGameState StartState,
Any particular reason you have StartState as a function argument but don't use it?

2024-02-25 04:22 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +	XComGameState StartState,
Removed the cargo cult

2024-02-25 21:29 UTC, Iridar approved these changes

2024-02-27 03:29 UTC, Tedster59 commented
Closing this and re-opening with a different branch in #1309 to fix github commit issues

2024-02-27 03:29 UTC, closed without merging