Re-add event to allow mods to adjust UFO interception time
X2CommunityCore/X2WOTCCommunityHighlander pull request #1317
Opened 2024-03-08 06:05 UTC by Tedster59

Fixes issue #1316.

This event existed in the LW2 Highlander as well as the [non-WOTC X2CommunityHighlander](https://github.com/X2CommunityCore/X2CommunityHighlander/blob/1d3a290f9f38d610dcc7bb1bef95f78df335a0d8/X2CommunityHighlander/Src/XComGame/Classes/XComGameState_UFO.uc#L115C27-L115C53). This pull request re-adds it and documents it so LWoTC can use this event for its original purpose of adjusting the UFO interception time for systems such as Long War that do not use the base game mission calendar.

2024-03-08 06:36 UTC, Iridar requested changes

2024-03-08 06:36 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_UFO.uc
> +
The empty line before the event trigger is unnecessary, and I would add Start / End Issue #### tags before the start of the docs and after the event trigger.

Also the docs could be formulated a bit better, like:

> The `PostUFOSetInterceptionTime` event allows mods to modify the state of a UFO
> after it has been created, but before the gamestate is submitted. 
> To use this event, listen to it with `ELD_Immediate` deferral and edit the state object received.

There's also this issue to consider: https://www.reddit.com/r/xcom2mods/wiki/index/events#wiki_important_note

In short, when listening to events using ELD_Immediate, the state objects passed as EventSource / EventData are taken from History. To modify the current version of the state object, listeners must explicitly get it from the NewGameState you should be passing with the event, otherwise you would be modifying History.

2024-03-09 01:06 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_UFO.uc
> +
Ok, this has been refactored and updated to shift the call up the stack and pass in NewGameState to the event.

2024-03-09 05:01 UTC, Iridar requested changes

2024-03-09 05:01 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_UFO.uc
> +	/// local XComGameState_UFO            UFOState;
Please use ```unrealscript <code> ``` tags around the example code, for example:

```
/// ```unrealscript
/// float GetPreDefaultAttackingDamageModifier_CH(
///         XComGameState_Effect EffectState,
///         XComGameState_Unit SourceUnit,
///         Damageable Target,
///         XComGameState_Ability AbilityState,
///         const out EffectAppliedData ApplyEffectParameters,
///         float CurrentDamage,
///         XComGameState NewGameState)
/// ```
```

Also, nitpicking, but I'd adjust docs a little:

"To use this event, listen to it with the `ELD_Immediate` deferral, and make sure to get the latest version of the UFO state object from the NewGameState, for example: <example code>".

2024-03-09 05:20 UTC, merged