Proposed fix for the persistent "Low Intel" warning after contacting all regions.
X2CommunityCore/X2WOTCCommunityHighlander pull request #1346
Opened 2024-05-11 12:50 UTC by Larryturbo

Fixes #1347 
The "Low Intel" warning shows up if your total intel is less than the contact cost of the next closest region. But if you've contacted all regions the cost defaults to 9999 and you get the warning despite not having more regions to contact. I've added an additional check to make sure your current resistance contacts aren't equal to the total number of regions that can be contacted (probably 16 but I didn't want to hardcode it) before the warning is displayed.

2024-08-03 16:18 UTC, BlackDog86 commented
Please can you squash all commits into a single commit?

2024-09-05 10:51 UTC, Iridar requested changes

2024-09-05 10:51 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
> +		if(XComHQ.GetCurrentResContacts() < class'X2StrategyElement_DefaultMissionSources'.static.GetAllRegions().Length)
I'm pretty sure you can't do `.Length()` on a dynamic array returned by a function. Stepped on these rakes too at some point. It's always just going to be zero.

2024-09-05 10:53 UTC, Iridar commented
Good find, but the code needs to be adjusted and actually tested, because right now I believe it will the Low Intel warning to just show never, because `class'X2StrategyElement_DefaultMissionSources'.static.GetAllRegions().Length` will evaluate to zero. 

Highlander is sirius business, please make sure to properly test all submissions.

Don't worry about squashing, it can be done during the merging process.

2024-09-09 14:53 UTC, Iridar commented
I tested, and while this solution works for the Low Intel popup, it doesn't work for the Low Intel warning in the lower left corner, and probably several other UI elements that use the `GetMinimumContactCost()` function, which is where the problem is. Thus, I suggest fixing the issue in that function instead.

2024-09-09 15:03 UTC, closed without merging