Updated OnUnitDied to properly kill gremlins when their owner dies
X2CommunityCore/X2WOTCCommunityHighlander pull request #1362
Opened 2024-07-24 21:22 UTC by BlackDog86

Fixes #367

Tested under 4 standard conditions:

Gremlin attached to specialist 1 - Kill specialist 1 - Gremlin dies
Gremlin attached to another unit - Kill other unit - Gremlin returns to specialist 1
Gremlin attached to another unit - Kill specialist 1 - Gremlin dies
Gremlin attached to specialist 1 - Kill other unit - No effect

And 4 non-standard conditions:

Specialist 1 uses aid protocol on specialist 2 - Kill specialist 2 - Gremlin 1 returns to Specialist 1, Gremlin 2 dies
Specialist 1 uses aid protocol on specialist 2 - Kill specialist 1 - Gremlin 1 dies, Gremlin 2 no effect
Specialist 1 & 2 use aid protocol on each other - Kill both specialists at once - Both gremlins die
Specialist 1 & 2 use aid protocol on 2 different units - Kill both units at once - Both gremlins return

2024-07-25 07:06 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +	/// easier to follow.
```suggestion
	/// Gremlins now correctly die when the Gremlin's owner dies while the Gremlin is attached to another unit.
```

I indented for Bugfix documentation to be shorter and worded in a user-facing way, so maybe this is enough? C.f. https://x2communitycore.github.io/X2WOTCCommunityHighlander/Bugfixes/

2024-07-25 07:06 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +		{
Can we change this condition to `!=` and swap the branches to more closely keep the original code structure?

2024-07-25 20:30 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +	/// easier to follow.
Done :)

2024-07-25 20:30 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +		{
And done :)

2024-08-10 19:23 UTC, robojumper reviewed
This could use a minor formatting pass - the original code doesn't look great either but this *adds* trailing whitespace. Also `If(UnitState.ObjectID != OwnerUnitState.ObjectID)` -> `if (UnitState.ObjectID != OwnerUnitState.ObjectID)`

2024-08-10 21:01 UTC, BlackDog86 commented
Should be sorted

2024-09-05 10:37 UTC, Iridar requested changes
Just make sure the codepath is not altered by none-checks. I.e. code that would run if either of the state objects was `none` should still run, as long as it doesn't actually require said state objects.

2024-09-05 10:37 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
>  	UnitState = XComGameState_Unit(EventData);
The original code is a bit awful about none-checking the unit state objects. Ideally, the checks should be done either right after getting the objects, or right before using them. This code does `if (UnitState.ObjectID != OwnerUnitState.ObjectID)`, and only then `if (OwnerUnitState != none`. `UnitState` itself is no longer none-checked at all. 

Obviously these are edge cases, but my experience tells me it's better to be extra careful with this.

2024-09-05 10:37 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
>  	if (UnitState.ObjectID == AttachedUnitRef.ObjectID || UnitState.ObjectID == OwnerStateObject.ObjectID)
With above in mind, I would change `if (UnitState.ObjectID == AttachedUnitRef.ObjectID || UnitState.ObjectID == OwnerStateObject.ObjectID)` into `if (UnitState != none && (UnitState.ObjectID == AttachedUnitRef.ObjectID || UnitState.ObjectID == OwnerStateObject.ObjectID))`

2024-09-05 10:37 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +		if (UnitState.ObjectID != OwnerUnitState.ObjectID)
And this into: `if (OwnerUnitState != none && UnitState.ObjectID != OwnerUnitState.ObjectID)`

2024-09-05 10:37 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +			if (OwnerUnitState != none && CosmeticUnit != none && CosmeticUnit.TileLocation != OwnerUnitState.TileLocation)
And then `OwnerUnitState != none` can be removed from here.

2024-09-12 02:41 UTC, Iridar commented
I've refactored the code, could you please redo your four tests with this code?
```cpp
function EventListenerReturn OnUnitDied(Object EventData, Object EventSource, XComGameState GameState, Name Event, Object CallbackData)
{
	local XComGameStateHistory History;
	local XComGameState_Unit UnitState, CosmeticUnit;
	local XComGameState NewGameState;
	local XComGameState_Item ItemState;
	local vector NewLocation;
	local XComGameStateContext_ChangeContainer ChangeContext;
	
	// Variable for Issue #367
	local XComGameState_Unit OwnerUnitState;
	
	// Start Issue #367
	/// HL-Docs: ref:Bugfixes; issue:367
	/// Gremlins now correctly die when the Gremlin's owner dies while the Gremlin is attached to another unit.
	
	UnitState = XComGameState_Unit(EventData);
	if (UnitState == none)
		return ELR_NoInterrupt;
	
	if (UnitState.ObjectID == OwnerStateObject.ObjectID)
	{
		// Owner of the Gremlin died, kill the Gremlin.
		
		History = `XCOMHISTORY;
		CosmeticUnit = XComGameState_Unit(History.GetGameStateForObjectID(CosmeticUnitRef.ObjectID));
		
		if (CosmeticUnit != none)
		{
			NewGameState = class'XComGameStateContext_ChangeContainer'.static.CreateChangeState("Owner Unit Died");
			ChangeContext = XComGameStateContext_ChangeContainer(NewGameState.GetContext());
			ChangeContext.BuildVisualizationFn = ItemOwnerDeathVisualization;
			CosmeticUnit = XComGameState_Unit(NewGameState.ModifyStateObject(CosmeticUnit.Class, CosmeticUnit.ObjectID));
			CosmeticUnit.SetCurrentStat(eStat_HP, 0);
			`GAMERULES.SubmitGameState(NewGameState);
		}
	}
	else if (UnitState.ObjectID == AttachedUnitRef.ObjectID)
	{
		// Unit to whom the Gremlin is attached to has died, recall the Gremlin and re-attach to its owner.
		
		History = `XCOMHISTORY;
		CosmeticUnit = XComGameState_Unit(History.GetGameStateForObjectID(CosmeticUnitRef.ObjectID));
		OwnerUnitState = XComGameState_Unit(History.GetGameStateForObjectID(OwnerStateObject.ObjectID));
		
		if (OwnerUnitState != none && CosmeticUnit != none)
		{
			NewGameState = class'XComGameStateContext_ChangeContainer'.static.CreateChangeState("Attached Unit Died");
			ItemState = XComGameState_Item(NewGameState.ModifyStateObject(Class, ObjectID));
			ItemState.AttachedUnitRef = OwnerStateObject;
			`GAMERULES.SubmitGameState(NewGameState);

			if (CosmeticUnit.TileLocation != OwnerUnitState.TileLocation)
			{
				NewLocation = `XWORLD.GetPositionFromTileCoordinates(OwnerUnitState.TileLocation);
				XGUnit(CosmeticUnit.GetVisualizer()).MoveToLocation(NewLocation);
			}
		}
	}
	// End Issue #367
	
	return ELR_NoInterrupt;
}
```

The bug with the original code happened mostly because it was convoluted and hard to read. Bad code. I don't doubt that the code you submitted fixes the bug, but it's still hard to read, so I've simplified it as much as possible.

2024-10-28 21:12 UTC, BlackDog86 commented
Refactored code testing:

Gremlin attached to specialist 1 - Kill specialist 1 - Gremlin dies CONFIRMED
Gremlin attached to another unit - Kill other unit - Gremlin returns to specialist 1 CONFIRMED
Gremlin attached to another unit - Kill specialist 1 - Gremlin dies CONFIRMED
Gremlin attached to specialist 1 - Kill other unit - No effect CONFIRMED

And 4 non-standard conditions:

Specialist 1 uses aid protocol on specialist 2 - Kill specialist 2 - Gremlin 1 returns to Specialist 1, Gremlin 2 dies CONFIRMED
Specialist 1 uses aid protocol on specialist 2 - Kill specialist 1 - Gremlin 1 dies, Gremlin 2 no effect CONFIRMED
Specialist 1 & 2 use aid protocol on each other - Kill both specialists at once - Both gremlins die CONFIRMED
Specialist 1 & 2 use aid protocol on 2 different units - Kill both units at once - Both gremlins return CONFIRMED

Looks like everything is fine with the refactor

2024-10-28 22:38 UTC, Iridar commented
Thank you.

2024-11-02 06:30 UTC, merged