Added a new EndBattleForceWin console function which finishes the tactical battle & completes all mission objectives
X2CommunityCore/X2WOTCCommunityHighlander pull request #1363
Opened 2024-07-24 23:21 UTC by BlackDog86

Fixes #386

2024-08-10 19:25 UTC, robojumper requested changes
There's also some weird formatting/indentation going on here.

2024-08-10 19:25 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalCheatManager.uc
> +	/// Add additional function which ends the tactical engagement while also forcing all objectives to be completed
This adds a *console command* and the documentation should mention the name of the console command.

2024-08-10 21:04 UTC, BlackDog86 commented
Updated

2024-09-05 09:58 UTC, closed without merging

2024-09-05 09:59 UTC, Iridar reviewed
Rejected.

2024-09-09 17:43 UTC, BlackDog86 commented
In that case I would close issue #386 as well then. I've asked XPanD to include the function in his console commands mod instead.