Add docs - Photobooth particle effect enuma
X2CommunityCore/X2WOTCCommunityHighlander pull request #1366
Opened 2024-07-27 11:33 UTC by BlackDog86

Adds docs for Issue #359

2024-08-10 19:28 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
> +		/// Randomise split left & right arms
This is clearly unrelated to `#359`, it's probably meant to be `#350`?

2024-08-10 21:09 UTC, BlackDog86 commented
![image](https://github.com/user-attachments/assets/443791c0-775c-4831-95db-b8d1542fecd0)
I think this commit references the wrong issue

2024-09-05 09:52 UTC, Iridar requested changes

2024-09-05 09:52 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
> -		// Start Issue #359
Looks like this was indeed meant to be Issue #350, but somehow somewhen got changed into #350? This is still a Highlander change, and needs to be marked by tags, so best not remove these, just change them to #350.

2024-09-05 09:52 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Photobooth.uc
> +	/// HL-Docs: ref:Bugfixes; issue:359
I don't think this qualifies as a bugfix.

2024-09-06 03:24 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Photobooth.uc
> +	/// HL-Docs: ref:Bugfixes; issue:359
Changed

2024-09-06 03:24 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
> -		// Start Issue #359
Done

2024-09-10 15:05 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
> +		/// HL-Docs: feature:PartsValidationOnTorsoChange; issue:350; tags:strategy
If this needed a HL-Docs entry, the correct syntax would be `HL-Docs: ref:PhotoboothParticleEffectEnums`. so that it gets automatically linked to the main HL-Docs entry elsewhere, but since there's no actual mod author facing changes here, I don't a HL-Docs entry is necessary here.

2024-09-10 15:09 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Photobooth.uc
> +	/// Add several additional enums for Photobooth Particle effects for mods to use
I'm a bit confused, I don't see any enums being added other than buffers and unstable ones. Does this issue actually add any enums that can be used by mod authors? If not, I'd adjust the comment to something like "Additional enums can be added here to be used by mods".

2024-09-10 17:12 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Photobooth.uc
> +	/// Add several additional enums for Photobooth Particle effects for mods to use
The base game X2Photobooth only contains the below for particle effect enums. Everything else in the CHL class was already added by the PR linked to issue #359. I've literally just added a docs entry for it, I have no idea what it's for - the issue was marked as 'needs docs' so I thought I'd try to help.
enum Photobooth_ParticleEffectType
```
{
	ePPET_None,
	ePPET_TemplarBladeRight,
	ePPET_TemplarBladeLeft,
	ePPET_TemplarShield
};

```

2024-09-12 02:59 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Photobooth.uc
> +	/// Add several additional enums for Photobooth Particle effects for mods to use
In that case I suggest adjusting it to "Add ~~severa~~l additional enums for Photobooth Particle effects for mods to use"

2024-11-02 04:51 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
> +		/// Randomise split left & right arms
Yep, fixed in other PR

2024-11-02 06:08 UTC, Iridar commented
This now has conflicts.

2024-11-02 10:06 UTC, closed without merging