Add docs - Gremlin customization
X2CommunityCore/X2WOTCCommunityHighlander pull request #1367
Opened 2024-07-27 11:59 UTC by BlackDog86

Adds docs for Issue #380

2024-09-05 09:39 UTC, Iridar requested changes

2024-09-05 09:39 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComUnitPawn.uc
> -	// End Issue #380
I see no reason to remove these two issue tags.

2024-11-02 01:29 UTC, Iridar commented
I'm sorry, but this still seems to remove Start Issue / End Issue tags in XComUnitPawn, what's up with that?

2024-11-02 04:09 UTC, BlackDog86 commented
> I'm sorry, but this still seems to remove Start Issue / End Issue tags in XComUnitPawn, what's up with that?

I explained this in the comment above -

The original file had this:
```
issue # X
<some code>
end issue # X    <---- remove this 
issue # X again <----- remove this 
<some code>
end issue # X 
```

Then you end up with
```
issue #x
<some code>
end issue #x
```

2024-11-02 06:13 UTC, Iridar commented
I see. 

The purpose of ref:Bugfixes docs is to be user-facing. As in, it should be treated as an entry in a changelog that explains the bug that is being fixed to Highlander users. If it's just a comment that explains to Highlander maintainers and Highlander-using mod authors, it doesn't need a docs entry.

Something like "Moved earlier so we can call SetAppearance() whether a new pawn is created or not" doesn't really explain what is being fixed here, so if you could reword it a bit, it would be appreciated.

2024-11-02 09:55 UTC, BlackDog86 commented
> I see.
> 
> The purpose of ref:Bugfixes docs is to be user-facing. As in, it should be treated as an entry in a changelog that explains the bug that is being fixed to Highlander users. If it's just a comment that explains to Highlander maintainers and Highlander-using mod authors, it doesn't need a docs entry.
> 
> Something like "Moved earlier so we can call SetAppearance() whether a new pawn is created or not" doesn't really explain what is being fixed here, so if you could reword it a bit, it would be appreciated.

Yep, I see what you mean. That should be done now.

2024-11-11 06:57 UTC, merged