Use List.ClearItems() instead of List.Itemcontainer.RemoveChildren() to prevent CTDs with large lists
X2CommunityCore/X2WOTCCommunityHighlander pull request #1373
Opened 2024-08-10 17:34 UTC by BlackDog86

2024-08-10 19:13 UTC, robojumper requested changes
One of these lines could probably use a Bugfixes comment like
```
/// HL-Docs: ref:Bugfixes; issue:1372
/// Fixed a potential crash when the Photobooth shows many list items.
```

Also, please add "Fixes #1372" to the PR description to link this PR to the related issue.

2024-08-10 19:13 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIPhotoboothBase.uc
> +	List.ClearItems();
This is missing a change comment.

2024-08-10 20:50 UTC, BlackDog86 commented
Changes made as requested

2024-09-05 09:28 UTC, Iridar commented
I assume this was tested and confirmed to fix the actual problem?

2024-09-05 14:48 UTC, Tedster59 commented
@Iridar  - Currently released as a standalone invasive MCO until the Highlander release here: https://steamcommunity.com/sharedfiles/filedetails/?id=3307455200, and this was also identified as the issue via Robojumper/Crash dump investigation

2024-09-06 02:21 UTC, BlackDog86 commented
> @Iridar - Currently released as a standalone invasive MCO until the Highlander release here: https://steamcommunity.com/sharedfiles/filedetails/?id=3307455200, and this was also identified as the issue via Robojumper/Crash dump investigation

That mod also does some other stuff with the UI - this fix literally just stops the crash, but leaves all the poses in a big list on the screen.

2024-09-08 19:15 UTC, Iridar approved these changes

2024-09-08 19:16 UTC, Iridar commented
I see. No reason to hold this up then. I checked and looks like these are the only places in code where `RemoveChildren()` is even called. It might be a good idea to add a comment that would caution against using it.

2024-09-08 19:19 UTC, merged