Set bConstantComplete to true for cleaned up particle systems
X2CommunityCore/X2WOTCCommunityHighlander pull request #1374
Opened 2024-08-15 03:24 UTC by Tedster59

Fixes #1201 based on crash dump analyzed by Robojumper and further discussion on discord, and implements Robojumper's suggested fix: https://discord.com/channels/165245941664710656/167912351763398657/1273396231011434517

2024-08-15 09:44 UTC, robojumper requested changes
I think we should additionally guard all calls to `EmitterPool.OnParticleSystemFinished` with a `!= None` check, and a comment that says something to the effect of:

```
// `EmitterPool.OnParticleSystemFinished` checks that the passed PSC is
// contained in the `ActiveComponents` array before doing anything with it,
// but not that the `PSC` is not None, in which case the function crashes with
// an access violation. It's unclear whether holes in the `ActiveComponents`
// can legitimately happen or indicate another bug, so the None check here
// is an additional defensive measure.
```

perhaps with a `` `REDSCREEN `` that shows when we would otherwise attempt to call `EmitterPool.OnParticleSystemFinished` with a None argument.

2024-08-15 16:09 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			/// mark the projectile bConstantComplete as true so that it will not be called again by EndConstantProjectileEffects and cause a crash.
makes sense,  Should I be documenting it as something else then, or just leaving out the HL-Docs reference all together?

2024-08-15 16:20 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			/// mark the projectile bConstantComplete as true so that it will not be called again by EndConstantProjectileEffects and cause a crash.
Updated to remove the HL-Docs reference

2024-09-04 23:50 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			if (Projectiles[i].ProjectileElement.UseProjectileType == eProjectileType_RangedConstant)
Shouldn't this `if (Projectiles[i].ProjectileElement.UseProjectileType == eProjectileType_RangedConstant)` statement encompass only the `Projectiles[i].bConstantComplete = true;` line? As it stands, adding this if() check will mean `OnParticleSystemFinished()` is never called for any non RangedConstant projectiles.

2024-09-04 23:50 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +				WorldInfo.MyEmitterPool.OnParticleSystemFinished(Projectiles[i].ParticleEffectComponent);
Since the crash seemed to be caused by calling `EmitterPool.OnParticleSystemFinished()` on a none-object, shouldn't we just guard every call of this function with none-checks just to be safe?

2024-09-05 01:14 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			if (Projectiles[i].ProjectileElement.UseProjectileType == eProjectileType_RangedConstant)
Maybe.  I borrowed that line from Robojumper as is as well as had confirmation from SwfDelicious.

![image](https://github.com/user-attachments/assets/a66e09d4-c6ae-434a-b411-4673f9ce76b4)

2024-09-05 01:19 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +				WorldInfo.MyEmitterPool.OnParticleSystemFinished(Projectiles[i].ParticleEffectComponent);
Doesn't the `if (Projectiles[i].ParticleEffectComponent == PSystem)` on line 1158 catch this? It can't be `none` if it equals `PSystem`

2024-09-05 07:51 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			if (Projectiles[i].ProjectileElement.UseProjectileType == eProjectileType_RangedConstant)
Definitely:

> There are probably a lot of ways to avoid the crash but I was thinking about something like this:
```
if (Projectiles[i].ProjectileElement.UseProjectileType == eProjectileType_RangedConstant) {
    Projectiles[i].bConstantComplete = true;
}
```
> in that function

2024-09-05 07:57 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +				WorldInfo.MyEmitterPool.OnParticleSystemFinished(Projectiles[i].ParticleEffectComponent);
My first instinct was to say "What if `PSystem` is `none` too?"

But it seems this function is only ever called as a delegate which is assigned as:
```
Projectiles[Index].ParticleEffectComponent.OnSystemFinished = OnParticleSystemFinished;
```
So effectively `ParticleEffectComponent` is the PS itself being passed to the delegate, which means it physically can't be none. So I guess it's fine to not do the check. I'd do it anyway though. We lose a only a few CPU cycles on it.

2024-09-05 09:19 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			if (Projectiles[i].ProjectileElement.UseProjectileType == eProjectileType_RangedConstant)
And this probably needs to be done *before* calling OnParticleSystemFinished() on it.

2024-09-05 14:13 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +			if (Projectiles[i].ProjectileElement.UseProjectileType == eProjectileType_RangedConstant)
Reordered the if check to only set the bConstantComplete variable

2024-09-05 14:13 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
> +				WorldInfo.MyEmitterPool.OnParticleSystemFinished(Projectiles[i].ParticleEffectComponent);
Added the none check

2024-09-05 14:17 UTC, Iridar approved these changes

2024-09-05 14:19 UTC, merged