REOPENED - Integrate Revival Protocol Fixes in CHL #1237
X2CommunityCore/X2WOTCCommunityHighlander pull request #1399
Opened 2024-10-29 00:06 UTC by BlackDog86

Reopening accidentally closed request.

Fixes Issue#1235 - Adds custom X2Condition to the RestoreActionPoints effect of Revival Protocol to prevent it from restoring APs to disoriented units. Updated the ability targetting condition to allow revival protocol to target stunned units, remove the stunned status and restore APs properly. Also integrated the additional targeting condition from RMs mod which allows the ability to target resistance soldiers. Discussion to be had over whether this part is required/necessary. 

Still requires finessing & testing before merge.

2024-11-02 06:26 UTC, Iridar commented
> allows the ability to target resistance soldiers. Discussion to be had over whether this part is required/necessary.

In cases like this I would defer to in-game localization and reasonable player expectations. 

Localization goes:

> "Send the GREMLIN to an ally to remove any negative mental status effects: Disoriented, Stunned, Panicked, or Unconscious."

"an ally" would reasonably include any allied unit, including resistance soldiers.

The ability itself engages the GREMLIN to perform actions on a unit, requiring no special training from the unit, other than being human or close enough to a human (Skirmishers), so a reasonable person would expect it to be able to target resistance soldiers.

So I'd say yeah, valid change.

2024-11-02 06:27 UTC, Iridar commented
This PR seems to be missing the .x2proj change with addition of new files.

2024-11-24 09:17 UTC, BlackDog86 commented
> This PR seems to be missing the .x2proj change with addition of new files.

Resolved :)

2024-11-27 13:32 UTC, Iridar commented
Sorry, but it needs to be in a separate commit.

2024-11-27 18:21 UTC, BlackDog86 commented
That should do it

2024-11-27 19:40 UTC, Iridar requested changes

2024-11-27 19:40 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_SpecialistAbilitySet.uc
> +	/// Update the ability template to call recover from stun & add a new condition to the Restore Action Point effect
Sorry, but I have to nitpick to these docs, they need to be user-facing and explain what specific bugs are getting fixed in plain terms.

2024-11-27 19:40 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_SpecialistAbilitySet.uc
> +	/// Restore APs on the unit only if the new X2Condition is met
This comment should be a simple double `//`

2024-11-27 21:32 UTC, BlackDog86 commented
Updated the docs to be more descriptive and removed the errant /

2024-11-28 11:37 UTC, Iridar commented
Closing this in favor of #1415, which adds more bugfixes.

2024-11-28 11:37 UTC, closed without merging