Allow forcing 24h clock and leading zeroes on month and date strings
X2CommunityCore/X2WOTCCommunityHighlander pull request #1401
Opened 2024-10-29 20:12 UTC by BlackDog86

2024-11-02 01:18 UTC, Iridar requested changes

2024-11-02 01:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGameData.ini
> +;bForce24hclock = true
Missing an "end Issue" comment tag, could probably just replace it with a single tag with issue number and following commend, something like:

; Issue #1400 - remove the semicolon at the start of the line to force 24H clock.

Also missing a new line at the end of the file.

2024-11-02 01:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		kTag.StrValue2 = 0 $ kDateTime.m_iDay;
Please use proper indentation.

2024-11-02 01:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +	local bool use24hclock;
Is this supposed to be `use12hclock`? Does this code even compile? I'm not sure why the additional variable is even necessary.

2024-11-02 01:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		// Issue #1400 - Add additional localization tags to allow mods to display days and months with leading zeroes
This seems like an opinionated change, it should be at least gated behind a separate config var.

2024-11-02 03:22 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Config/XComGameData.ini
> +;bForce24hclock = true
Yep OK - done

2024-11-02 03:22 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		kTag.StrValue2 = 0 $ kDateTime.m_iDay;
Fixed

2024-11-02 03:24 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +	local bool use24hclock;
Yeah, that was a mistake, apologies - I've removed the var altogether now and just used !default.bForce24hClock directly in the expression.

2024-11-02 03:29 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		// Issue #1400 - Add additional localization tags to allow mods to display days and months with leading zeroes
this isn't really a change at all - the default localization file uses this for the display of dates:
`m_strMonthDayYearShort="<XGParam:IntValue2/><XGParam:StrValue1/!SeparatorString/><XGParam:IntValue0/><XGParam:StrValue1/!SeparatorString/><XGParam:IntValue1/>"` This would not change at all with the code adjustment. A mod would have to specifically remove the localization line and replace it with <XGParam:StrValue2> or <XGParam:StrValue3> explicitly in order for this to adjust base-game behaviour at all so I don't think a config gate is necessary.

2024-11-02 06:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		// Issue #1400 - Add additional localization tags to allow mods to display days and months with leading zeroes
Does this have to be a Highlander change then? It this does nothing without mod-supplied localization lines, what's stopping the mod that is adding those lines from adding its own localized tags and using the tag expand handler to fill them with whatever date format it wants?

2024-11-02 09:36 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		// Issue #1400 - Add additional localization tags to allow mods to display days and months with leading zeroes
Because the mod would need to MCO X2StrategyGameRulesetDataStrcutures just to create a couple of tags which is quite an invasive MCO for a very small change (plus there are already some mods existing MCOing other parts of this, creating conflicts. I thought this sort of thing is more or less exactly what CHL is for?)

2024-11-11 06:55 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
> +		// Issue #1400 - Add additional localization tags to allow mods to display days and months with leading zeroes
I don't understand why would MCO be necessary. You can create arbitrary tags and fill them with arbitrary content via the DLC Hook, no MCO required. Mods can always ship their own adjusted version of `GetTimeStringSeparated()` to use in their tags.

2024-11-12 20:03 UTC, BlackDog86 commented
After a bit of further investigation & for the purposes of clarity, the only place that the 'short' date is actually called for in the base game, is in the memorial screen. However, other mods (such as beat's mission history) also call for it. See below some examples of the display options:
Memorial before:
![image](https://github.com/user-attachments/assets/75d7c9b6-8145-453e-adb2-851112c75f1a)
Memorial after, swapping the short date tags:
![image](https://github.com/user-attachments/assets/2d5773e6-d30c-4c9d-8be7-2def78a6263f)

Clock example, base game:
![image](https://github.com/user-attachments/assets/ad344bea-8fca-48bb-b575-3c86930166c0)
Clock example with bforce24hclock and bforce24hclockleadingzero on:
![image](https://github.com/user-attachments/assets/5df75dac-2801-4c13-9ce8-9d257f0d29bf)
Clock example with bforce24hclock and bforce24hclockleadingzero on and using tag swapping to swap the long dates as well:
![image](https://github.com/user-attachments/assets/1b212cc9-1b46-4183-831d-1f0877cfbe9a)

I should say that the save and load game screens do not use this function and have their own logic for parsing the save file headers to display the dates of the save games. This logic isn't great either in my view and in one of my own mods I MCO a few of the classes responsible in order to display those dates differently (https://steamcommunity.com/sharedfiles/filedetails/?id=3268722967). This is the output of that mod, for example:
![image](https://github.com/user-attachments/assets/9d92663b-3b53-4f62-a835-18965accf7f8). The base-game code is a bit janky in that area as well but making that better is out of scope for this, which is just making a few small changes for the sake of flexibility.

2024-11-12 20:37 UTC, BlackDog86 commented
Hmm something weird happened in testing. Don't merge this yet please - need to check something!

2024-11-14 13:34 UTC, Iridar commented
For context to the above discussion, I didn't understand that the following pipeline was in place:

1. Different parts of the code call the `GetDateString()` function
2. Which takes one of the two existing strings that exist solely for the purpose of arranging date
3. Expands its tags
4. Returns the formatted date to whatever code caled the function

So I didn't understand why changes to `GetDateString()` were necessary.

2024-11-14 13:35 UTC, merged