Add a new event trigger after Mission Intro kismet has completed
X2CommunityCore/X2WOTCCommunityHighlander pull request #1407
Opened 2024-11-12 16:25 UTC by furudee

Fixes issue #1406

2024-12-02 23:27 UTC, Iridar requested changes

2024-12-02 23:27 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
> +	/// HL-Docs: ref:PostMissionIntroKismet
Don't need a HL-Docs entry here, just the standard issue tags are enough. Could even do `// Single Line for Issue #1406`.

2024-12-02 23:27 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
> +	/// ```unrealscript
HL-Docs for events have a different style, here's an example:

```
/// ```event
/// EventID: AllowOnCovertActionCompleteAnalytics,
/// EventData: [
///   inout bool bAllow,
///   in Object OriginalEventData,
///   in Object OriginalEventSource,
///   in XComGameState OriginalGameState,
///   in name OriginalEvent,
///   in Object OriginalCallbackData
/// ],
/// EventSource: none,
/// NewGameState: none
```

Also, are you sure there's no useful stuff you could pass along with the event trigger?

2024-12-03 03:41 UTC, furudee commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
> +	/// HL-Docs: ref:PostMissionIntroKismet
I figured that the reference would be useful, since there are two different places where the trigger is placed and both will show the location on the documentation

2024-12-03 03:50 UTC, furudee commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
> +	/// ```unrealscript
I'm not sure there is anything special to pass with the trigger, since there is no pending gamestate and you can access the ruleset normally when the event trigger is called

2024-12-04 13:59 UTC, Iridar approved these changes

2024-12-04 13:59 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
> +	/// HL-Docs: ref:PostMissionIntroKismet
That's fair. Good work.

2024-12-04 14:00 UTC, Iridar commented
This is ready to go. I'll merge it when the work on 1.30 starts in earnest. Thanks for your contribution.

2024-12-04 14:01 UTC, Iridar commented
Btw it wasn't mandatory to squash the commits, when you're not adding new files, all commits can be squashed automatically during the merging process, we require exactly two commits only when new files are added to CHL.

2024-12-16 14:54 UTC, merged