Add validation for X2TargetingMethod_ArcWave:GetAdditionalTargets
X2CommunityCore/X2WOTCCommunityHighlander pull request #1409
Opened 2024-11-14 18:14 UTC by furudee

Issue #1408

Needs testing with other mod abilities to make sure nothing breaks

2024-11-30 17:11 UTC, furudee commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_ArcWave.uc
> +			for (i = AdditionalTargets.AdditionalTargets.Length - 1; i >= 0; --i)
Yes, that would be smarter I believe. I made it a loop due to the "validation" concept.

Now that I looked at how to implement this again, I figured that emptying the additional target array of the function parameter at the start might be the easiest solution, since the function will fill out the array with correct targets anyway.
Unless I'm missing something that can have an ability have any other additional targets or secondary effects that are not related to the tiles being hit by the ability

2024-12-02 23:23 UTC, Iridar requested changes
Another unfortunate issue is that Highlander guidelines require that PRs that add new files to source must have the file addition in one commit, and everything else associated with the Issue in the second commit. This PR now has three commits, the two last commits must be squashed together before I can merge this PR.

2024-12-02 23:23 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_ArcWave.uc
> +	/// Empty the additional target array, since it can already have incorrectly assigned targets by native code
The Bugfixes docs must be like a changelog entry, they need to explain the nature of the bug and how it is getting fixed.  Something like: "Fix bug with Arc Wave targeting where it could hit enemies that were not targeted by the player" or something along those lines.

2024-12-03 03:39 UTC, furudee commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_ArcWave.uc
> +	/// Empty the additional target array, since it can already have incorrectly assigned targets by native code
I've squashed the two commits to one and rephrased the doc entry

2024-12-04 13:58 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_ArcWave.uc
> +	/// Empty the additional target array, since it can already have incorrectly assigned targets by native code
Looks good to me. I think this is ready for merge, but just to confirm, did you run some tests with the new implementation to check it's fixing the issue?

2024-12-04 15:16 UTC, furudee commented
Diagnosing another issue related to arcwaves and came across this:

In UITacticalHUD_AbilityContainer::ConfirmAbility where the GetAdditionalTargets function is called, it checks to see if the function returns true before overwriting the array:

		if( TargetingMethod.GetAdditionalTargets(AdditionalTarget) )
		{
			//	overwrite target to include data from GetAdditionalTargets
			AvailableActionInfo.AvailableTargets[TargetIndex] = AdditionalTarget;
		}

Should the GetAdditionalTargets function be changed to always return true, since we would like to overwrite the array if it has no valid additional targets?

In the edge-case where TargetedPawn != none or Tiles.Length > 1, it would return false and thus not overwrite the array

2024-12-04 16:44 UTC, furudee commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_ArcWave.uc
> +	/// Empty the additional target array, since it can already have incorrectly assigned targets by native code
Yes, it appears to be working

![pic](https://github.com/user-attachments/assets/b2ee5f23-2612-41b4-8f4d-b72f4c995d71)

2024-12-04 18:04 UTC, Iridar commented
Alright, this is good to go then. I'll look at the other issue.

2024-12-16 14:53 UTC, merged