Swap "UI is busy" checks to a more robust function
X2CommunityCore/X2WOTCCommunityHighlander pull request #1418
Opened 2024-11-30 04:44 UTC by Tedster59

Fixes issue #1417 by updating all uses of `(StrategyMap != none && StrategyMap.m_eUIState != eSMS_Flight && !`HQPRES.ScreenStack.IsCurrentClass(class'UIAlert')`

to a helper function written by @Xymanek for Covert Infiltration that checks if the current screen is the strategy map instead of just checking that an alert is present.

![image](https://github.com/user-attachments/assets/6910dbab-f1cf-419e-830b-e7c889a974df)

This will solve edge cases where two geoscape entities try to throw UI popups at the same time, such as a Covert Action returning during the UFO chase and allowing an Avenger Defense mission to be skipped.

2024-12-01 23:26 UTC, Iridar requested changes

2024-12-01 23:26 UTC, Iridar commented on Components/DLC2CommunityHighlander/DLC2CommunityHighlander/DLC2CommunityHighlander.x2proj
> +    <Content Include="Src\DLC_2\Classes\X2DownloadableContentInfo_DLC_Day60.uc">
This seems to be in the wrong commit.

2024-12-01 23:26 UTC, Iridar commented on Components/DLC2CommunityHighlander/DLC2CommunityHighlander/Src/DLC_2/Classes/X2DownloadableContentInfo_DLC_Day60.uc
> +		/// Use a more robust check to determine if the game should trigger the update.
The docs for bugfixes should be user-facing and akin to a changelog, I.e. "This is fixing bug X that can occur when Y". And just one HL-Docs entry is enough, others can be just regular Issue tags. The appropriate place for HL-Docs would be above the new helper function.

2024-12-01 23:26 UTC, Iridar commented on X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
>      </Content>
Also in the wrong commit.

2024-12-02 01:12 UTC, Tedster59 commented on Components/DLC2CommunityHighlander/DLC2CommunityHighlander/DLC2CommunityHighlander.x2proj
> +    <Content Include="Src\DLC_2\Classes\X2DownloadableContentInfo_DLC_Day60.uc">
Fixed

2024-12-02 01:13 UTC, Tedster59 commented on X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
>      </Content>
Fixed

2024-12-02 23:03 UTC, merged

2024-12-17 22:29 UTC, Tedster59 commented
Ok, so this causes a mod to break the game, because said mod swaps the geoscape for a subclass using a UISL.
https://steamcommunity.com/sharedfiles/filedetails/?id=1161736731

```
`HQPRES.StrategyMap2D = `HQPRES.Spawn(class'Override_UIStrategyMap', `HQPRES);
```

I expect this is causing the following check to fail:

```
StrategyMap.Movie.Pres.ScreenStack.GetCurrentScreen() == StrategyMap;
```