Adjust voiceline checks in X2Action_ApplyWeaponDamageToUnit and add a dynamic delay to the 'SquadMemberDead' voiceline
X2CommunityCore/X2WOTCCommunityHighlander pull request #1421
Opened 2024-12-07 15:56 UTC by BlackDog86

Fixes Issue #1398

2024-12-07 17:12 UTC, BlackDog86 commented
Happy with the checks on X2Action_ApplyWeaponDamageToUnit is working properly but the delayed 'SquadMemberDead' line is not working quite right. If the visualizer progresses immediately onto something else (e.g. if alien unit 1 kills xcom unit 1 then alien unit 2 does something straight afterwards), the visualiser can progress onto the next action before playing the squadmemberdead line. So relying on idle state of the visualizer is not fully effective. I tried with static delays earlier in testing, which admittedly were better than overlapping with the dead screams, but depending on what other stuff was going on in that visualization block, usually meant it overlapped with other stuff (explosions, people falling off buildings and taking more damage etc. etc.). Work still required.

2024-12-10 10:17 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +function DelaySpeechSquadMemberDead()
This should be marked as `private`, unless it interferes with the functionality.

2024-12-10 10:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +	kIsRobotic = IsRobotic();
Styling, but since it's just going to be used once, there's no need to store the output in a variable, could just call the function directly.

2024-12-10 10:20 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +//	local XGUnit SurvivingUnit;
And marking these comment-outs with issue tags.

2024-12-10 10:21 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +;;; Issue #1398 - Change to adjust the delay of the 'Squad member dead' voiceline after a unit is killed
Suggested change:

> The delay between an XCOM unit being killed and another XCOM unit playing the 'Squad member dead' voiceline

2024-12-10 10:23 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Action_ApplyWeaponDamageToUnit.uc
> +		// Start Issue #1398 - Don't play 'Taking Damage' voiceline if unit was killed or incapacitated
Since you're changing just one like, I think a single issue tag would be more appropriate.

Simple `// Issue #1398 - Don't play 'Taking Damage' voiceline if the unit was killed or incapacitated` should be enough.

2024-12-10 10:24 UTC, Iridar requested changes
This is mostly good to go, just needs minor docs / styling changes.

2024-12-10 10:34 UTC, Iridar commented
Tested, works great.

2024-12-10 19:33 UTC, BlackDog86 commented
Pushed a new version with your requests - Just need to test it after making that function private before finalising.

2024-12-10 19:49 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +var config int fSquadMemberDeadVoicelineDelay;
This is `int` now? Was this always int? It should be float.

2024-12-10 19:50 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +	/// Additionally, it adds a delay to the 'Squad Member Dead' voicelines to reduce interference with deathscream
> interference

Technical term is "overlap" :)

2024-12-10 19:50 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +private function DelaySpeechSquadMemberDead()
The function needs its own Start/End Issue tags.

2024-12-10 19:50 UTC, Iridar requested changes
Needs just a bit more hair-licking.

2024-12-11 01:31 UTC, BlackDog86 commented
Should be good to go - did a quick test and making the function private and changing the variable to float type hasn't effected anything functionally that I could notice.

2024-12-11 01:31 UTC, BlackDog86 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +var config int fSquadMemberDeadVoicelineDelay;
Think it was, changed now

2024-12-16 14:52 UTC, merged