Add a check if a WWise voiceline exists to prevent attempts to play missing voicelines
X2CommunityCore/X2WOTCCommunityHighlander pull request #1422
Opened 2024-12-08 14:20 UTC by furudee

Fixes issue #1419 

The implementation can be expanded to check if SoundCues exist, if so is wished, yet it's redundant since in `XComCharacterVoice::PlaySoundForEvent` it makes such check before playing a soundcue voiceline

2024-12-08 17:33 UTC, BlackDog86 commented
I tested this earlier today and it does indeed have the intended effect (fixing missing voicelines of hero units with personalities / attitudes by falling back to the default voiceline if the attitude voiceline doesn't exist). So I'm OK with it, can you confirm in testing from your side as well?

2024-12-08 18:31 UTC, furudee commented
Yes, it seemed like it works, exactly as you said. I also tested with a random voicepack soldier and soundcues seem to pass through the function normally

2024-12-10 10:09 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +function bool CheckAkSpeechExists(Name Speech)
This is internal CHL function and should be marked as `private`.

2024-12-10 10:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +	if(XComHumanPawn(m_kPawn).Voice != None && XComHumanPawn(m_kPawn).Voice.AkBankName != "")
CHL code convention is to include a space after if, i.e. do `if (Condition)`, not `if(Condition)`.

2024-12-10 10:14 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +	if(nHushedSpeech != '' && CheckAkSpeechExists(nHushedSpeech))
Changes must be marked with Start Issue / End Issue tags.

2024-12-10 10:14 UTC, Iridar requested changes
This is mostly good to go, just needs some docs / code styling changes. Good work.

2024-12-10 16:52 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +	if(nHushedSpeech != '' && CheckAkSpeechExists(nHushedSpeech))
Initially I meant something like this:

```cpp
if (nHushedSpeech != '' && AkSpeechExists(nHushedSpeech)) // Issue #1419 - add an AkSpeechExists() condition
{
	m_kPawn.UnitSpeak(nHushedSpeech);
}
else if (nPersonalitySpeech != '' && AkSpeechExists(nPersonalitySpeech)) // Issue #1419 - add an AkSpeechExists() condition
{
	m_kPawn.UnitSpeak(nPersonalitySpeech);
}
else if (AkSpeechExists(nCharSpeech)) // Issue #1419 - add an AkSpeechExists() condition
{
	m_kPawn.UnitSpeak(nCharSpeech);
}
```
However, now that I've looked at the original code, it's a poorly formatted mess, so they way you've ended up doing it is fine, with just one pair of Start - End Issue tags. 

However, I would be more explicit with the the comment then. Something like: 

`// Start Issue #1419 - Perform an AkSpeechExists() check before calling m_kPawn.UnitSpeak()`

I'll do it myself via web interface so you don't have to.

2024-12-10 16:54 UTC, Iridar commented
This is good to go. Thank you.

2024-12-16 14:52 UTC, merged