Fixes for item stacking behaviour
X2CommunityCore/X2WOTCCommunityHighlander pull request #1433
Opened 2024-12-27 11:17 UTC by BlackDog86

Fixes #1429 
Fixes #1352

This PR does a number of things:
1. Provides a configurable array of items in CHHelpers (set up by default to include all of the TLE Weapons) for which the onAcquired function should be run to create the attachments when the item is equipped. This is needed to avoid a bug where equipping stacked copies of TLE weapons causes the attachments to be stripped off.
2. Heavily adjusts the HasUnModified item function to improve stacking behaviour for all items (items with identical attachments now stack together in the inventory).
3. Fixes two current issues with PCS items where if they have 0 stat boosts, they do not stack at all, and if they have >1 stat boost, only the first stat boost is checked and the items are stacked, even though they shouldn't be.

I've tested using debug strat, additem commands and a couple of missions with a minimal modlist and everything seems OK but I've yet to test in a fully modded campaign setup.

2024-12-27 15:55 UTC, Larryturbo commented
"items with identical attachments now stack together in the inventory"
As long as it can still see the weapon's colour and pattern as a difference. When multiple soldiers unequip their weapon for wherever reason, using the colour is how I can tell who dropped what.

2024-12-27 16:32 UTC, BlackDog86 commented
Will have to test that - I imagine that customising the weapon sets the 'force unique' flag but I'll be away from the PC for a few days so not sure if I'll be able to test / address this at least until the new year.

2024-12-27 16:40 UTC, faanlez commented
`HasBeenModified()` does not check `WeaponAppearance` at all, it only cares about nickname and weapon upgrades. So with these changes identically upgraded weapons will stack and they will all get the same appearance. But, keep in mind that soldiers actually have their own weapon customization saved to them that they will use over the weapon's own customization *unless* `HasBeenModified()` returns `true`.

2024-12-27 18:15 UTC, Larryturbo commented
Then upgraded and customized weapons will lose their appearance and stack. That should never be the case.

2024-12-27 20:25 UTC, BlackDog86 commented
Fair enough - It should be easy enough to revise to take account of customisation to be fair. If you force the behaviour to work 'correctly' & no-stack everything it makes a royal mess of the strategy debug start inventory and I do think having non unique items with the same attachments stacking makes sense (the original code in that function is downright awful) so I'd prefer to revise it that way than just blanket no-stack everything which isn't infinite but yeah - fixing the other two issues without playing with the item stacking behaviour is also perfectly possible.

2025-01-01 12:15 UTC, BlackDog86 commented
Updated PR now checks weapon appearances when putting items back into the inventory and ensures that upgraded weapons with custom appearances do not stack (non-upgraded weapons / infinite items continue to set the default weapon appearance on the soldier which is used if no custom appearance is already set on the weapon).

This means:
Two yellow magnetic rifles with a scope, = stack
1 x Blue and 1 x Yeloow magnetic rifle with a scope = no stack
Two yellow magnetic rifles, one with a scope and one with a stock = no stack

Does that seem reasonable? I've also added the chosen weapons to the 'OnEquipFix' array so their attachments don't get stripped (so if, for whatever reason) mods decided to add multiple copies of the chosen weapons they wouldn't get stacked and have their attachments removed just like the TLE weapons.

2025-01-01 14:50 UTC, BlackDog86 commented
Well the alternative is basically patching all of the weapons in X2Item_TLE_Weapons so that they fire the onAcquired function when you equip them, which is also a perfectly reasonable solution but I'm not sure if we're even allowed to modify that file since we don't have a 'TLE Highlander' as far as I know.

If I can't create a manual array of templates and I can't modify the templates, then I fail to see how the issue can be fixed.

2025-01-04 10:58 UTC, Iridar commented
Why is simply not stacking weapons with *any* weapon upgrades attached is not an option?

2025-01-05 04:01 UTC, BlackDog86 commented
Of course, not stacking weapons with any upgrades is an option. Simply removing the check for number of slots in HasBeenModified() is sufficient to do that & implementing it that way also has the benefit of not needing to run the onacquired function when equipping the weapon (and thus no need for the config array), since the bit that strips the attachments in GetItemFromInventory can't happen if the weapons aren't stacked in the first place.

That said, when you just do the simple fix, what happens is HasBeenModified then *correctly* returns true for all items with attachments and it unstacks all the items created by strategy debug start (which is basically 10 x copies of every non-infinite item) so you get this:
![20250105035012_1](https://github.com/user-attachments/assets/19f165e5-b744-4e67-bf9e-77a63e0a4312)

I couldn't find the code that's responsible for doing this but if we can find it, perhaps we can use the event in HasBeenModified to over-ride the stacking behavior for those items.

Honestly, unstacking items in strat debug isn't a big deal for me & I'm perfectly happy to sacrifice a debug annoyance for better in-game control of the inventory so I can adjust the PR to just deal with the two explicit issues / bugs and not do anything regarding improving the item stacking behaviour, which I guess is probably the preferred approach.

2025-01-05 05:40 UTC, Iridar commented
Yeah, that's better. I'll do a proper review later. To be clear, my main issue wasn't with configurable array itself, but more with filling it in Highlander. If you want, you can still add a configurable array of stackable items with upgrades, but it must be empty by default.

2025-01-05 05:40 UTC, Iridar commented
And I'd probably prefer it done in a separate PR.

2025-01-05 05:48 UTC, BlackDog86 commented
Makes sense - it would be a lot easier, now I understand how these functions work, to make a configurable feature in a new PR, allowing items with identical attachments & appearance to stack. I agree it's better that way.

2025-01-05 08:38 UTC, Iridar requested changes
Good work, but needs hair-licking.

2025-01-05 08:38 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +			hasIdenticalStatBoosts = false;
What is the purpose of this line?

2025-01-05 08:38 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +	local bool hasIdenticalStatBoosts;
Variable naming conventions would have these as `StatBoostIdx` and `bHasIdenticalStatBoosts`.

2025-01-05 08:38 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +						// Begin Issue #1352
Begin Issue tag should be above the HL-Docs entry. I would also reword the docs:

> Fix bug that caused PCS items that did not provide exactly one stat boost to not stack properly in the UI by making `HasUnModifiedItem()` properly compare items with multiple stat boosts or no stat boosts at all.

2025-01-05 08:38 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +						if(CombatSimTest.StatBoosts.Length != 0)
Missing empty space after `if` and `for` in this entire code block.

2025-01-05 08:38 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> -	WeaponTemplate = X2WeaponTemplate( m_ItemTemplate );
Generally it's preferable to not fix multiple issues in one PR, so that later they can be reverted separately if necessary. So I'm gonna have to ask you to separate this into two PRs.

2025-01-05 08:38 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +	/// logic in GetItemFromInventory and PutItemInInventory, causing attachments to be stripped when the stacked item is equipped.
I'd reword docs:

> Fix bug that caused weapons that have weapon upgrades installed, despite not having any weapon upgrade slots, to stack in the HQ inventory, causing them to lose their installed upgrades. The fix removes the check for the number of weapon upgrade slots on the weapon from the logic that determines whether the item has been modified or not, and leaving just the check for installed weapon upgrades.

Though feel free to leave the mention of the downstream logic if you want.

2025-01-06 08:09 UTC, merged