Add bunch of knockback fixes
X2CommunityCore/X2WOTCCommunityHighlander pull request #1437
Opened 2024-12-29 15:21 UTC by furudee

Fixes Issue #1431
This request does a few things:

1. Makes `WorldData.GetAllActorsTrace` a line trace by commenting out Extents, since it often got stuck on ground, curbs and other floor tiles. I assume the logic was that units cannot be knocked down from buildings and other high places
2. Units may now take fall damage from falling from such high places, and units landed on take damage. After whatever gamestate the knockback is in, I create a delegate to make a new falling gamestate to deal with the falling action.
3. Units may fly over other units and land on them, if they're high enough to take fall damage. Before it ended and set the knockback location before the unit you're flying over.
4. Adds custom visualization tree merging logic when fall is triggered by a knockback. This removes the `X2Action_Falling` node from the build tree, since otherwise the unit will "fall down" twice. A normal falling context caused by destruction of floor beneath the unit shouldn't end up at the newly added segment, but I'm not certain

And since it's a quite large fix, I would like it to be tested more

2025-01-04 11:06 UTC, Iridar commented
Looks very intriguing, I can't really follow the code, so we'll just have to do some extensive testing.

2025-01-06 16:43 UTC, BlackDog86 commented
Fixes #1431

2025-06-26 04:05 UTC, Tedster59 commented
Looks good to me, want to see proper testing

2025-06-26 11:29 UTC, furudee commented
A while ago I released this fix as [a standalone mod ](https://steamcommunity.com/sharedfiles/filedetails/?id=3474547616) and I haven't had people complain that it doesn't work: 
one user said that it crashed their game after finishing a mission when they installed it mid-campaign, but I think it's because it MCO'ed `XComGameStateContext_Falling`, and I wasn't aware that any MCO that overrides state classes or context classes will crash your game if installed/removed mid-campaign (I think)

2025-06-29 02:55 UTC, Tedster59 requested changes
For now, marking Request Changes, because this needs rewriting to not store runtime variables at the template level.

2025-06-29 02:55 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Knockback.uc
> +var XComGameState_Unit FallingUnit;
This is very bad.  Causes garbage collection errors on mission end.  need to rewrite this and the lines below it, anything that is runtime should be kept inside the functions.

2025-06-29 02:55 UTC, Tedster59 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Knockback.uc
> +						if ((StartTile.Z - TempTile.Z) < 4)
Should this be opened to config? or is 4 the "standard" height.

2025-06-29 20:04 UTC, furudee commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Knockback.uc
> +						if ((StartTile.Z - TempTile.Z) < 4)
It's `iStoryHeightInTiles` local variable from `XComGameStateContext_Falling::ContextBuildGameState`, so a hardcoded value

2025-06-29 20:08 UTC, furudee commented
I have amended the PR to do all the operations inside functions so avoiding putting any new global variables that caused a garbage collection crash, now the PR only has one added new file `X2Effect_Knockback` and the previous file `XComGameStateContext_Falling` has been removed

2025-06-29 22:06 UTC, Tedster59 approved these changes
Changes look good.  Have you tested the updated version?

2025-06-30 01:03 UTC, Tedster59 commented
Convo from discord:

Units damaged by another unit landing on them don't play a damage animation for now, can be fixed later.  Functionally this still works.  Merging for now so we can get some extra testing with a beta CHL release

2025-06-30 01:03 UTC, merged

2025-08-16 23:24 UTC, BlackDog86 commented
Noting that this issue is closed, it creates a warning when compiling CHL - 

Instead of doing this:
```
local X2Action_ApplyWeaponDamageToUnit DamageAction;
DamageAction = X2Action_ApplyWeaponDamageToUnit(class'X2Action_ApplyWeaponDamageToUnit'.static.AddToVisualizationTree(ActionTrack, VisualizeGameState.GetContext(), false, KnockbackAction));
```

You can just call the function without assigning it to a variable and then not manipulating the variable :)
`class'X2Action_ApplyWeaponDamageToUnit'.static.AddToVisualizationTree(ActionTrack, VisualizeGameState.GetContext(), false, KnockbackAction));` should be sufficient.