Unrestrict Psi PCS to PsiOperative class (#602)
X2CommunityCore/X2WOTCCommunityHighlander pull request #733
Opened 2020-01-20 18:00 UTC by boundir

Hope I did everything right this time 😅

2020-01-20 18:57 UTC, MrNiceUK commented
For consistency, would consider removing the explicit `IsPsiOperative()` check, and just include `PsiOperative` in the config list. I've done similar where I've changed hard coded lists into config lists.

2020-01-20 20:16 UTC, boundir commented
I accept that challenge.

2020-01-20 21:37 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIInventory_Implants.uc
> +	/// HL-Docs: feature:UnrestrictPsiPCS; issue:602; tags:tactical,compat
```suggestion
	/// HL-Docs: feature:UnrestrictPsiPCS; issue:602; tags:tactical,strategy
```

I haven't documented this anywhere yet (I will!), but the `compat` tag is meant for "hey, this can cause compatibility issues".

2020-01-20 21:43 UTC, boundir commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIInventory_Implants.uc
> +	/// HL-Docs: feature:UnrestrictPsiPCS; issue:602; tags:tactical,compat
Oops understood this as "hey this will extend compatibility" 😂 Tried and failed.
Do you want me to rebase and push again?

2020-01-20 21:44 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIInventory_Implants.uc
> +	/// HL-Docs: feature:UnrestrictPsiPCS; issue:602; tags:tactical,compat
There's a "Commit suggestion" button you can use to immediately apply my suggested change from the web interface

2020-02-12 10:22 UTC, pledbrook approved these changes
We may end up having a specific documentation strategy for config variables like this, but I have no idea when that will be agreed upon. No need to hold up this PR for it, I think.

2020-09-03 13:43 UTC, Iridar requested changes

2020-09-04 14:46 UTC, Iridar approved these changes

2020-10-24 10:47 UTC, pledbrook commented
I merged this in manually so that I could squash commits 2-4. Wow, this one's been waiting in line for a while. Sorry it took so long!

2020-10-24 10:47 UTC, closed without merging