Changes to item upgrade system
X2CommunityCore/X2WOTCCommunityHighlander pull request #734
Opened 2020-01-21 07:39 UTC by GingerAvalanche

Implements Issue #93 changes
Implements Issue #289 changes

Allows any item type to be upgraded, and allows for upgrade slot handling on a per-state basis.

Retry of #732, this time without being a 2 year old branch.

2020-02-12 10:30 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +				class'X2EventManager'.static.GetEventManager().TriggerEvent('ItemUpgraded', UpgradedItemState, none, NewGameState); // Issue #289 - handle upgrades for infinite items
Please use
```
`XEVENTMGR.TriggerEvent(...)
```
in place of
```
class'X2EventManager'.static.GetEventManager().TriggerEvent(...)
```

2020-02-12 10:30 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +					class'X2EventManager'.static.GetEventManager().TriggerEvent('ItemUpgraded', UpgradedItemState, BaseItemState, NewGameState); // Issue #289 - handle upgrades for utility items like grenades and m
Same goes here and anywhere else in the pull request.

2020-02-12 10:32 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +				class'X2EventManager'.static.GetEventManager().TriggerEvent('ItemUpgraded', UpgradedItemState, none, NewGameState); // Issue #289 - handle upgrades for infinite items
In addition, these events will need [highlander docs](https://x2communitycore.github.io/X2WOTCCommunityHighlander/#documentation-for-the-documentation-tool) associated with them. There are examples in various pull requests and in the current `master` branch of the highlander (I recommend rebasing this branch against it).

2020-02-12 10:33 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +// This function fires an event that mods can listen for which will allow them to modify upgrade slots on a per-gamestate basis
HL-Docs needed here too.

2020-05-16 02:27 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +// This function fires an event that mods can listen for which will allow them to modify upgrade slots on a per-gamestate basis
Done. Also wrote the docs for #260 which needed them.

2020-05-16 02:27 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +					class'X2EventManager'.static.GetEventManager().TriggerEvent('ItemUpgraded', UpgradedItemState, BaseItemState, NewGameState); // Issue #289 - handle upgrades for utility items like grenades and m
Done.

2020-05-16 02:27 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +				class'X2EventManager'.static.GetEventManager().TriggerEvent('ItemUpgraded', UpgradedItemState, none, NewGameState); // Issue #289 - handle upgrades for infinite items
Done. https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/734/commits/d45d155bc6327454d846cfdb9503f83089a1d4be

2020-05-16 02:30 UTC, GingerAvalanche commented
First time I've managed to rebase properly! \o/ All requested changes should be resolved, but I can't figure out how to get the pr to consider them resolved in the final summary.

2020-10-24 00:09 UTC, GingerAvalanche commented
Alright, after about a hundred force-pushes because I didn't realize what files had what changes in any given commit snapshot, this PR now looks clean and should be easy to tell what it changes.

2021-01-08 23:09 UTC, Iridar requested changes
Had to locally rebase this onto the current master to build it.

I have tested the features in this PR and they seem to be working fine, although upgrading non-weapon items requires an external UI mod, such as Mod Everything Reloaded.

I did have a few nitpicks to documentation and implementation, but other than that this is good to go.

2021-01-08 23:09 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +				`XEVENTMGR.TriggerEvent('ItemUpgraded', UpgradedItemState, none, NewGameState);
This should probably have event docs, for example:
```
/// ```event
/// EventID: ItemUpgraded,
/// EventData: XComGameState_Item,
/// EventSource: none,
/// NewGameState: yes
/// ```
```
Also, when you have "```event", the "events" tag is not necessary.

Although not sure how event docs should look like, seeing as you use the same EventID, but with different EventData / EventSource availability.

2021-01-08 23:09 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +					`XEVENTMGR.TriggerEvent('ItemUpgraded', UpgradedItemState, BaseItemState, NewGameState); // Issue #289 - handle upgrades for utility items like grenades and medkits
Probably should mark other trigger events with single line HLDocs:

/// HL-Docs: ref:ItemUpgraded

2021-01-08 23:09 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +/// In general, it should only be used if you have some type of handling that allows
Please add event docs to this, for example:
```
/// ```unrealscript
/// EventID: OverrideLostSpawnIncreaseFromUse
/// EventData: XComLWTuple {
/// 	Data: [
///       inout int LostSpawnModifier,
///       in XComGameState_Ability ActivatedAbilityState,
///     ]
/// }
///	EventSource: self (XComGameState_Unit)
/// GameState: no
/// ```
```

2021-01-08 23:09 UTC, Iridar commented on docs_src/docs/dlcinfo.md
> +Many of the Highlander's features utilize function calls to the subclasses of
Not sure this is supposed to be here.

2021-01-10 01:00 UTC, Iridar commented
Closing this PR in favor of #941, which ships the same changes with better docs.

2021-01-10 01:00 UTC, closed without merging