Allow mods to prevent CA completion from counting towards campaign stats
X2CommunityCore/X2WOTCCommunityHighlander pull request #769
Opened 2020-02-08 14:35 UTC by Xymanek

Closes #752

TODO:
* [ ] Docs (after #742 is merged)

2020-09-03 14:43 UTC, robojumper approved these changes

2020-10-24 12:39 UTC, pledbrook requested changes

2020-10-24 12:39 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/AnalyticsManager.uc
> +	if (!TriggerAllowOnCoverActionComplete(EventData, EventSource, GameState, Event, CallbackData))
Shouldn't this be `TriggerAllowOnCovertActionComplete()`?

2020-10-24 12:39 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/AnalyticsManager.uc
> +/// EventID: AllowOnCoverActionCompleteAnalytics
Should be `AllowOnCovertActionCompleteAnalytics`

2020-10-24 13:15 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/AnalyticsManager.uc
> +	if (!TriggerAllowOnCoverActionComplete(EventData, EventSource, GameState, Event, CallbackData))
![image](https://user-images.githubusercontent.com/2865341/97082679-27557100-1614-11eb-83ea-4a418b335490.png)

Same response for the other comment

2020-12-08 11:49 UTC, pledbrook commented
Someone else will have to merge this because I refuse to propagate a deliberate misspelling that will just cause mod authors grief when they can't work out why their event listeners aren't working.

2021-02-07 12:33 UTC, robojumper requested changes
I agree with Peter that this should use the correct spelling. Point out the discrepancy in the documentation if you'd like.

2021-05-26 08:19 UTC, Xymanek commented
Rebased to resolve the merge conflict

2021-05-26 09:51 UTC, pledbrook approved these changes

2021-05-26 09:53 UTC, pledbrook commented
@robojumper Do you want to re-review this, or shall we just move to "ready for merge" already?

2021-05-27 19:26 UTC, robojumper approved these changes

2021-05-28 08:36 UTC, merged