Fix covert action report if rewards prevented (#810)
X2CommunityCore/X2WOTCCommunityHighlander pull request #813
Opened 2020-03-19 08:49 UTC by pledbrook

The covert action report will no longer display soldiers as gaining XP or cohesion if the rewards have been prevented from being given. This is because the reward prevention code also prevents the soldiers from gaining XP and cohesion.

I have also added documentation for the CovertAction_PreventGiveRewards event.

Fixes #810.

2020-04-07 09:16 UTC, pledbrook commented
I don't know, it seems more of a bug that the report displays XP gain when the soldiers aren't actually gaining XP.

2020-04-07 09:34 UTC, pledbrook commented
Made the trigger function non-static and clarified that it's for internal use only and hence not covered by the backwards compatibility policy.

2020-04-13 09:04 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +// *Note* This is not part of the highlander's public API, so it is not covered
```suggestion
// *Note* This function (not the event) is not part of the highlander's public API, so it is not covered
```

2020-04-26 13:20 UTC, pledbrook commented
@Xymanek I've just realised that the reward popup is shown after the covert action report screen is closed. For example, if a reward was a scientist and the reward was blocked by a listener, the "scientist awarded" popup still appears.

At this point, I'm wondering whether it makes sense to add a "bRewardsNotGiven" boolean to `XCGS_CovertAction`, which is set after the event is fired the first time. Then the other code that depends on whether the reward was given or not can read it from the action state rather than triggering the event again. Thoughts?

2020-04-30 18:59 UTC, Xymanek commented
It will definitely prevent issues with non-idempotent listeners. However, adding state variables can always cause issues with in-progress saves, so need to be careful

2020-10-23 08:43 UTC, pledbrook commented
I've now switched to using a state variable whose default value is `false`, which should mean it has no impact on existing campaigns.

2021-01-15 02:19 UTC, Iridar approved these changes
LGTM, though I don't know much about covert actions, and haven't tested this.

2021-02-07 21:22 UTC, robojumper reviewed
Approach LGTM. Docs should be updated to the "new" format.

2021-02-14 10:49 UTC, Xymanek requested changes

2021-02-14 10:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UICovertActionStaffSlot.uc
> +				if (!Unit.bCaptured && !GetAction().RewardsNotGivenOnCompletion)
```suggestion
				if (!Unit.bCaptured && !ActionState.RewardsNotGivenOnCompletion)
```

2021-02-14 10:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UICovertActionStaffSlot.uc
> +				// not granted in that case).
Add `HL-Docs: ref:`

2021-02-14 10:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +var bool									RewardsNotGivenOnCompletion;
```suggestion
var privatewrite bool RewardsNotGivenOnCompletion;
```

To prevent desync, IMO the variable should only be settable by the event's result

2021-02-14 10:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +// to use it themselves.
I do not see a purpose for this comment. 

* `Trigger[...]` methods are private all over the CHL and none of them get a dedicated "this is private ..." comment
* If I want to be naughty, I would just copy paste the code and trigger the event manually

2021-02-14 10:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +/// on the covert action get no XP or cohesion.
I think it makes sense to also mention that "the results are saved and are used to adjust UI later"

2021-02-14 10:49 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +	// End Issue #810
I see no reason why this would prevent the `TriggerNextCovertActionPopup` part. IMO this check should be after that block.

Also. add `HL-Docs: ref:`

2021-05-24 09:50 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +	// End Issue #810
Do you mean you don't see why it *should* prevent the popups? If so, probably agreed, although I'm not sure which popup the `NextCovertActionPopup` is.

2021-05-24 09:51 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +	// End Issue #810
Ah right, they're in reverse order. So this is the one that gives the player the option to go straight to the resistance ring to queue up another covert action.

2021-05-25 13:10 UTC, Xymanek requested changes

2021-05-25 13:10 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +/// ```
Needs update to the current doc format

2021-05-26 09:27 UTC, pledbrook commented
Fixed docs (after multiple tries). This should be squash merged once approved and ready for merge.

2021-06-03 07:26 UTC, Xymanek approved these changes

2021-06-03 07:27 UTC, merged

2021-06-09 15:26 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +var bool									RewardsNotGivenOnCompletion;
And this just broke some code in LWOTC 😆 Now I need to work out a way for a failed Ambush mission to fail the covert action.

2021-06-10 16:26 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +var bool									RewardsNotGivenOnCompletion;
Do you want to revert the PR while you figure it out?

2021-06-10 16:31 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
> +var bool									RewardsNotGivenOnCompletion;
No, it's fine. Fortunately the ambush mission completes before the prevent-give-rewards event fires. So I'm just storing the mission outcome in a game state object that my prevent-give-rewards listener reads to determine whether the CA failed or not. A much better solution that modifying that variable directly :smile: So all's Gucci.