Implements Issue #832
X2CommunityCore/X2WOTCCommunityHighlander pull request #833
Opened 2020-04-02 08:37 UTC by RustyDios

Added code to the Interpolate Weapon function that allows modders to adjust the weapon pawn position by entries in the XComUI config file.
Adds the struct required for the entries.
Adds the var config entry for the function

2020-04-02 09:02 UTC, RustyDios commented
Hmm.. forgot to add the new locals to the function
local Vector BeginLocation, Offset;
local XComGameState_Item Weapon;
local int i;

2020-04-02 14:08 UTC, robojumper commented
Could you also fix #39? `PreviewUpgrade` sets the `PawnLocationTag` for the upgrade and then at the end of the function calls `CreateWeaponPawn` which resets the `PawnLocationTag` to the weapon location tag.

2020-04-03 07:43 UTC, Musashi1584 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
> +	//===============================================
```suggestion
// Start Issue #832
```
to be consistent with general commenting pattern

2020-04-03 07:43 UTC, Musashi1584 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
> +	//===============================================
```suggestion
	//	End Issue #832
```

2020-04-03 07:45 UTC, Musashi1584 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
> +		if (X2WeaponTemplate(Weapon.GetMyTemplate()).DataName == default.WeaponViewOffsets[i].Template )
```suggestion
		if (Weapon != none &&
		    X2WeaponTemplate(Weapon.GetMyTemplate()) != none &&
		    X2WeaponTemplate(Weapon.GetMyTemplate()).DataName == default.WeaponViewOffsets[i].Template
		)
```

2020-04-04 07:03 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
> +		{
2 possible improvements:

1) Move the `Weapon != none` check outside the loop - it will never produce different results inside the loop anyway
2) Replace `X2WeaponTemplate(Weapon.GetMyTemplate()) != none && X2WeaponTemplate(Weapon.GetMyTemplate()).DataName == default.WeaponViewOffsets[i].Template` with `Weapon.GetMyTemplateName() == default.WeaponViewOffsets[i].Template`

2020-04-13 08:23 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
> +		{
I don't understand why this was resolved without the suggested changes being implemented or challenged.

2020-04-13 11:40 UTC, Musashi1584 commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
> +		{
Probably the changes were overriden by the force push because there were not pulled before :/

2020-09-02 20:52 UTC, Iridar requested changes
I've tweaked and cleaned up the code to conform to Highlander standards, please update when you can: 

https://pastebin.com/BrvGtLZM

(EDIT @robojumper: patch that can be applied with `git apply` https://pastebin.com/5GYGxnBT)

2020-09-02 22:35 UTC, Iridar commented
Requested changes are implemented and tested, approving PR.

2020-09-02 22:35 UTC, Iridar approved these changes

2020-10-24 09:46 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
> +	local int Index;
For future reference, please use a start and end comment for multi-line changes like this, otherwise it's not clear which variables are specifically relevant to the issue. In other words, something like:
```
// Start Issue #832
local Vector BeginLocation, Offset;
local XComGameState_Item WeaponState;
local int Index;
// End Issue #832
```
I will merge this pull request anyway; this is just a request for the future.

2020-10-24 09:50 UTC, merged