Implements #859 changes
X2CommunityCore/X2WOTCCommunityHighlander pull request #860
Opened 2020-05-16 23:18 UTC by GingerAvalanche

2020-09-03 15:05 UTC, robojumper requested changes
Looks sound to me, but docs will not render correctly.

2020-09-03 15:05 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +/// * An object, the item's X2ItemTemplate
We don't really have a strict schema for Tuple contents documentation but this will be unreadable in the rendered document.

2020-09-03 15:05 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_BlackMarket.uc
> +/// * An array of ints, the ObjectIDs for states with buy prices
Same here, this at least needs a newline before the bullet point list.

2020-09-04 15:12 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +/// * An object, the item's X2ItemTemplate
Markup’s always gotta look different on every platform, doesn’t it? :P

Is there a way to see what the docs will look like before I upload? I’m used to single asterisk being bullet point and double asterisk being indented bullet point. Not really sure how to resolve that if I can’t see what I’m doing.

2020-09-04 15:16 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +/// * An object, the item's X2ItemTemplate
Locally: See https://x2communitycore.github.io/X2WOTCCommunityHighlander/#documentation-for-the-documentation-tool

You can also push another commit to re-run the checks, then download the artifact by clicking the green checkmark next to the commit, choosing "details", clicking "Artifacts" and downloading the HTML bundle. Unless you run it on a webserver, the stylesheets will be missing, but the HTML markup will be visible.

2020-10-22 00:14 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_BlackMarket.uc
> +/// * An array of ints, the ObjectIDs for states with buy prices
Resolved.

2020-10-22 00:16 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +/// * An object, the item's X2ItemTemplate
I wish the docs would support nested bullet points, though I realize that would be very difficult, given that spaces at the beginning of newlines would have ambiguous purpose, between differently-indented bullet points and just plain old clean comment formatting. Doesn't stop me from hating it, though.

2020-10-22 00:18 UTC, GingerAvalanche commented
Original commit split into file-add and changes, subsequent commits squashed into first edit commit for readability.

ready-for-review tag, can't change, blah blah blah.

2020-10-22 00:25 UTC, GingerAvalanche commented
Realized I left an unedited file out of the unedited file commit split, so I went back and redid that one. Now it should be good to go.

2020-10-24 13:08 UTC, pledbrook requested changes

2020-10-24 13:08 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +	Tuple.Data[2].o = ItemTemplate;
There's a significant mismatch between the docs and this code. The docs imply this:
```
Tuple.Data[0].kind = XComLWTVString;
Tuple.Data[0].s = strImage;
Tuple.Data[1].kind = XComLWTVString;
Tuple.Data[1].s = strTitle;
Tuple.Data[2].s = m_strCostLabel;
Tuple.Data[3].s = ItemPrice;
Tuple.Data[4].s = strInterest;
Tuple.Data[5].s = ItemTemplate.GetItemBriefSummary(ItemRef.ObjectID);
```
Note that `Item.ObjectID` and `ItemTemplate` are not documented.

In addition, `.as` is not intended just to group different properties of the same type together. It's more for properties that *are* arrays of strings.

One last thing: do you need to pass the template? Can't a listener get that from the item state object if it needs it?

2020-10-24 13:08 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_BlackMarket.uc
> +	`XEVENTMGR.TriggerEvent('BlackMarketBuyPricesUpdated', Tuple, History);
There is no need to pass `XComGameStateHistory` as the event source. This can be retrieved on demand from anywhere. Plus, is the history really the event source logically speaking? It might make sense to pass the Black Market state object as the event source.

2020-10-24 13:08 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_BlackMarket.uc
> +	`XEVENTMGR.TriggerEvent('BlackMarketBuyPricesUpdated', Tuple, History);
Also, as before, I really dislike polluting base game code with plumbing like this. I would prefer to see it factored out into a separate function.

2020-10-24 13:08 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_BlackMarket.uc
> +/// * An array of ints, the prices
This should follow the standard format for event definition documentation, just as you used for the other event.

2020-10-24 13:08 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_SellItem.uc
> +	Tuple.Data[0].as.Add(4);
This is very confusing. You scale the array to accept one item. You then use `AddItem()`, which automatically scales the dynamic array to fit in the new item, and then you scale it to 4 items without adding any more.

As before, I really don't think you should be using `.as` here. Just a normal string tuple field works fine and is simpler.

2020-10-24 13:22 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +///       inout string strImage - the image to display for the item
The way #908 is implemented, this won't parse, both because that PR switches from `XComLWTuple { Data: [ ... ] }` to simply `[ ... ]` and because comments aren't supported. I'm willing to accept this for now though and rebase #908 after this is merged and change this in that PR.

Feedback about a comment column being useful hereby noted.

2020-10-24 13:49 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +///       inout string strImage - the image to display for the item
I settled on this because I saw it was done this way in another, existing doc and I was tired after committing about a half-dozen changes just to see the docs fail to render properly. There was no way to do indented bullet points, so I just gave up. If there's another way to handle this that will actually render properly, I'll gladly do it that way, instead.

2020-10-24 13:54 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +///       inout string strImage - the image to display for the item
This is fine this way, no need to hold up the PR because another, not yet merged PR changes the format again.

2020-10-24 14:06 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +	Tuple.Data[2].o = ItemTemplate;
Docs mismatch is wholly due to the fact that I was using an unfamiliar format to document, because, as mentioned on the doc comment, the docs don't support indented bullet points. I'll go back and try to understand that format in another way, or see if I can find a way to make the readable format render properly, but trying to explain nested collections with our doc format has proven incredibly frustrating so far.

That being said, it sounds like the tuple format I inadvertently put into the docs would be the preferred format. In which case, I can simply refactor the code to match the docs, instead of the other way around.

No. I do not need to pass the template.

2020-10-24 14:11 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +	MC.QueueString(Tuple.Data[0].as[4]);
Can you give me an example of "as done elsewhere"? I followed the examples of previous issues when I set it up in this manner, so I'm not sure where I should be looking.

Also, I have no idea how I'm supposed to set this up to use named variables without manually assigning return values from the separate function to those named variables, which, wouldn't that just be replacing the plumbing with slightly less plumbing? Maybe I'll understand once I can see what you mean.

2020-10-24 14:17 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_BlackMarket.uc
> +/// * An array of ints, the prices
The last review I received on the other event stated there was no standard format. Is there a place where these formats are documented?

2020-10-24 14:29 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_SellItem.uc
> +	Tuple.Data[0].as.Add(4);
I did this because it's firing the same event as `UIBlackMarket_Sell:PopulateItemCard()` so that one listener can respond to events from both functions, as what data is used in this function is also used in that one. It cleans up the code on the mod end of things. I leave those indices empty because this function doesn't care about the data that the other function puts into those indices.

I didn't feel the need to include this function in the documentation because this function's purpose is incidental to `PopulateItemCard()`'s - an author would expect that when that function performs a job, this one will perform its job in tandem. This firing of the same event is simply to uphold that expectation.

This also means that those empty strings would/will still be necessary if I turn the `.as` into five `.s`'s.

2020-10-24 15:04 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +	MC.QueueString(Tuple.Data[0].as[4]);
Here's one simple example: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/master/X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAdventOperations.uc#L252

And another one here: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/master/X2WOTCCommunityHighlander/Src/XComGame/Classes/UIResistanceReport.uc#L162

Hope that helps. If you have any more questions, let me know. A large chunk of these functions begin `TriggerOverride`, so you could also search for that in the code base to see more examples.

2020-10-24 15:20 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_BlackMarket.uc
> +/// * An array of ints, the prices
Well, there's a pre-#908 standard that the doc generation uses, and the #908 standard. I think the idea is to go back and change the old style to the new in previous commits/pull requests. I think it might help that transition if you use the same form as you did earlier in this PR for the `BlackMarketItemCardPopulated` event.

Alternatively, just add the line
```
//(/) FIXME: Update to new event specification (#908)
```
to the comment block somewhere so that it can be identified easily.

2020-10-24 15:24 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_SellItem.uc
> +	Tuple.Data[0].as.Add(4);
OK, thanks for the explanation. I'll need to think some more on this. I'm not really keen on the idea of padding event data just so the same listener can be used for both events. One approach would be to simply make ItemFriendlyName the first element of the `Data` array and then listeners can just not bother with the other elements if `Data` only has length 1.

Anyway, let me think about it.

2020-10-24 22:45 UTC, GingerAvalanche commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIBlackMarket_Sell.uc
> +	MC.QueueString(Tuple.Data[0].as[4]);
Aha! Many thanks, I've gotten so used to Python recently that I forgot you can specify primitive-type arguments as `out` and it'll pass a reference to the argument instead of the literal.

2021-01-09 21:40 UTC, Iridar commented
Per discussion on discord, leaving this PR for @pledbrook to handle.

2023-08-10 16:03 UTC, Iridar commented
It's dead, Jim.

2023-08-10 16:03 UTC, closed without merging