Implements #866 fix
X2CommunityCore/X2WOTCCommunityHighlander pull request #867
Opened 2020-05-19 02:30 UTC by GingerAvalanche

2020-09-03 15:14 UTC, robojumper requested changes

2020-09-03 15:14 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIStaffContainer.uc
> +	/// Navigator.GetSelected(), which should always focus the correct UIPanel.
Bugfixes should have a comparatively short documentation, see https://x2communitycore.github.io/X2WOTCCommunityHighlander/Bugfixes/ .

Feel free to keep the detailed explanations as a regular comment.

2020-10-21 23:19 UTC, GingerAvalanche commented
Resolved requested changes and split the commit into two for easier detailing of my actual changes.

2020-10-22 11:18 UTC, pledbrook approved these changes
Seems to work just fine, thanks. I would prefer a commit message that doesn't rely on someone having to follow a link just to find out the what and why of the commit, but I can live with it.

2020-10-24 10:51 UTC, robojumper approved these changes

2020-10-24 11:02 UTC, merged