Loading saves hook
X2CommunityCore/X2WOTCCommunityHighlander pull request #870
Opened 2020-05-23 06:49 UTC by Xymanek

Closes #808

2020-09-03 15:16 UTC, robojumper approved these changes

2020-10-24 10:24 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
> +/// An example would be making state changes due to updates in the mod.
I personally find this description ambiguous and had to look at the code to understand what was meant. I suggest an alternative:

```suggestion
/// The base game already provides the OnLoadedSavedGame hook, which is called when a mod is added to
/// XCOM 2 after the saved game that's being loaded was saved. In other words, when a game is saved, it
/// records which mods are active at that time. This hook then notifies a mod if a saved game that doesn't
/// have a record of that mod is loaded.
///
/// However, there are cases when mods need to react when saved games that do already have references
/// to them are loaded. In other words, the mods were active when the game was saved, but they still want
/// to handle situations when that saved game is loaded again. For example, they may want to make state
/// changes due to updates in the mod itself.
```

It still sounds awkward to me, but it's somewhat clearer.

2020-12-27 03:29 UTC, Xymanek commented
Note to self: also add a note regrading cases where in-tactical saves are loaded

2021-01-15 02:49 UTC, Iridar commented
I've read through the docs carefully, and I still do not understand the purpose of this PR. What can it do what cannot be done by using `OnLoadedSavedGameToStrategy()` and `OnLoadedSavedGameToTactical()` together? 

Judging by the code, assuming I read it correctly, this is meant to be an opposite to `OnLoadedSavedGame()`, which runs if the mod wasn't active when the save was made, while `OnLoadedSavedGameWithDLCExisting()` runs *only* if the mod was active when the save was made? 

If my understanding is correct, perhaps the docs should mention this fact *before* going into great details about the game's logic, as well as why would anyone need it *over* other existing tools.

I have particular gripes with these lines:

> what happens if the mod is "existing" but wants to make state changes before the save is loaded?

The mod uses `OnLoadedSavedGameToStrategy()` and `OnLoadedSavedGameToTactical()`.

> `OnLoadedSavedGameWithDLCExisting` fills that gap - it is called every time a save is loaded

Eeeeeexcept the case if the mod wasn't present when the save was made. Highly misleading, because this made me think this was some sort of `AnySaveGameLoaded()` hook, so, like Peter, I had to look at the code.

2021-02-07 21:57 UTC, robojumper requested changes
So one reason this *should* exist in some form is that the existing hooks happen after some of presentation layer stuff etc. has already loaded. The new hook and `OnLoadedSavedGame` run immediately after deserializing the History, which is super important for doing migration work on the save file.

But yes, the one doc line that says "every time a save is loaded" needs to be changed.

2021-02-11 11:12 UTC, Xymanek commented
@robojumper the docs have been significantly expanded but I forgot to update the "better compare" link which is why you were probably looking at the old version.

I updated the link - please take a look again

2021-02-11 13:10 UTC, robojumper requested changes

2021-02-11 13:10 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
> +/// Important note 1: this will not be called when the base game OnLoadedSavedGame is called ("new" mods).
Please don't use "important note" to contradict something said in a paragraph earlier. Directly say that `OnLoadedSavedGameWithDLCExisting` is only called when loading a save file where this mod was previously recorded as "existing" and omit the note.

2021-02-11 13:10 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
> +/// If the above is too limiting for your use case, consider using `OnLoadedSavedGameToStrategy`/`OnLoadedSavedGameToTactical`.
"... which are called after the relevant listener templates are registered and most of the presentation has loaded."

2021-02-11 13:10 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
> +/// Important note 4: the list of "existing" mods is not cleared when the mod is removed (in order to facilitate the popup).
Maybe mention that this list of existing mods is maintained and checked on a DLCName (`*.XComMod` file) basis.

2021-02-19 10:31 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
> +/// Important note 1: this will not be called when the base game OnLoadedSavedGame is called ("new" mods).
> contradict something said in a paragraph earlier

I fail to see any contradiction - could you please be more specific about which part you were referring to?

2021-02-19 10:35 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
> +/// Important note 4: the list of "existing" mods is not cleared when the mod is removed (in order to facilitate the popup).
I would prefer to have a centralized resource that explains DLCIndentifiers and how they relate to the one set in DLCInfo's config and the common mistake that happens there. If we have one now, I could link to it, but I see no reason to block this PR on this point.

I know that #965 mentions this stuff, but I don't think it's a good idea to link to it since it's not merged yet

2021-04-20 08:58 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
> +/// Important note 1: this will not be called when the base game OnLoadedSavedGame is called ("new" mods).
> `OnLoadedSavedGameWithDLCExisting` fills that gap - it is called every time a save is loaded

followed by:

> this will not be called when the base game OnLoadedSavedGame is called ("new" mods)

I am assuming that @robojumper is requesting a change to the first sentence so that it doesn't say that the hook is called every time, since it's not. I agree with that as it's a bit confusing.

2021-05-30 14:56 UTC, Xymanek commented
Squashed down to 2 commits, addressed the comments regarding docs (I believe) and rebased to get rid of the merge conflict

2021-06-02 06:58 UTC, Xymanek commented
I think it doesn't make sense to hold this PR for #1003. In fact, when #1003 is implemented, it can directly change all 3 references, rather than requiring "cooperation" from this PR

2021-06-03 08:34 UTC, Iridar approved these changes
Looks like you adjusted the docs since the last time I looked. It's much clearer now, although I'm still not sure what kind of use case this hook could have that is not filled by `OnLoadedSavedGameToStrategy`/`OnLoadedSavedGameToTactical`, but I assume you have a good reason for it, so I'm not gonna be the one to wall it. Approved.

2021-06-03 09:50 UTC, pledbrook approved these changes

2021-06-03 10:28 UTC, merged