Allow mods to override starting region link constraints
X2CommunityCore/X2WOTCCommunityHighlander pull request #929
Opened 2020-12-23 11:17 UTC by pledbrook

`XComGameState_RegionLink.IsEligibleStartRegion()` now fires an 'OverrideAllowStartingRegionLink' event that allows mods to override the rule for whether a region can be linked to a potential starting region or not. The same event is used to bring `RemoveNonContinentLinks()` and `XComGameState_WorldRegion.CanBeStartingRegion()` into line with `IsEligibleStartRegion()`.

The event takes the form:
```
  EventID: OverrideAllowStartingRegionLink,
  EventData: [ in XComGameState_WorldRegion LinkedRegion, inout bool AllowLink ],
  EventSource: XComGameState_WorldRegion (potential starting region),
  NewGameState: StartState
```

Resolves #774.

Note that this pull request depends on #928.

2021-02-07 13:06 UTC, robojumper requested changes

2021-02-07 13:06 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +/// EventSource: XComGameState_WorldRegion (potential starting region),
```suggestion
/// EventSource: XComGameState_WorldRegion (PotentialStartRegion),
```

This is going to be a variable name in the template

2021-04-07 08:42 UTC, pledbrook commented
I've merged @Grobobobo 's changes into the second commit for tidiness and added a line to the docs to clarify that the event passes a start state (not just any old new game state).

2021-04-07 09:11 UTC, robojumper approved these changes

2021-04-09 09:57 UTC, Xymanek requested changes

2021-04-09 09:57 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +/// to any neighboring region.
Please mention that `RegisterInCampaignStart` is required to properly consume this event

2021-04-09 09:57 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +/// **Note:** Event listeners are passed a *start state* for `NewGameState`.
Considering that `StartState`s 

* don't get submitted and visualized as normal/usual states do
* are not pending at the point the `TriggerEvent` is called

I don't think it's a good idea to pass it into the event system. You could pass it as a tuple argument, but i don't see a point since one could easily get it from `History.GetStartState()` - i suggest removing it from event arguments entirely

2021-04-09 09:57 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
> +// compatibility will not be guaranteed.
```suggestion
// **NOTE** This is public so that it can be called from XComGameState_WorldRegion
// too. This is **not** intended to be used by mods and as such is not a part of the highlander's 
// public API - backwards compatibility is not guaranteed.
```
IMO this better conveys the idea

2021-05-26 06:39 UTC, Xymanek approved these changes

2021-05-26 09:40 UTC, merged