Fix smoke and poison grenade targeting and effects
X2CommunityCore/X2WOTCCommunityHighlander pull request #930
Opened 2020-12-25 10:35 UTC by pledbrook

Grenades that apply effects to the world, such as smoke grenades, are unreliable in their targeting because those effects are not always applied to tiles that are highlighted by targeting. This change adds two boolean config vars that, when true, fix that so that smoke and/or poison are applied to all the highlighted tiles.

In addition, there are some instances where the targeting will highlight units without highlighting the tiles that they're on. This gives the impression that those units will be affected by the world effects (like smoke) when they won't. This changes adds a config array of grenade names, where any grenade in that array will not highlight units unless they are on highlighted tiles. Smoke grenades and bombs are the main candidates for this array, but mods may add other types.

Resolves #669

2020-12-25 10:39 UTC, pledbrook commented
I don't envisage any issues with Reliable Smoke mod, because it MCOs `X2Effect_SmokeGrenade` and `X2Effect_ApplySmokeGrenadeToWorld`. Yes, it overrides the CHL settings when it does that, but only to do the same thing. It should even benefit from the `GrenadesRequiringUnitsOnTargetedTiles` setting if the player adds grenades to it.

2020-12-26 10:15 UTC, pledbrook commented
Save file that demonstrates the issue, if anyone wants it for testing:

[save_BUG Smoke targeting.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/5742932/save_BUG.Smoke.targeting.zip)

Just try the targeting with the smoke bomb on the Specialist(?), aiming at various points amid the three soldiers that are close to one another (which includes the Specialist).

To test the fix, add these lines to user config *XComGame.ini*:
```
[XComGame.CHHelpers]
DisableExtraLOSCheckForSmoke=true
DisableExtraLOSCheckForPoison=true
GrenadesRequiringUnitsOnTargetedTiles=SmokeGrenade
GrenadesRequiringUnitsOnTargetedTiles=SmokeGrenadeMk2
GrenadesRequiringUnitsOnTargetedTiles=DenseSmokeGrenade
GrenadesRequiringUnitsOnTargetedTiles=DenseSmokeGrenadeMk2
```

2021-02-07 20:50 UTC, robojumper requested changes
Config changes are definitely OK, `CheckForTargetsOnTiles` seems fine with a caveat.

2021-02-07 20:50 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_Grenade.uc
> +					if (CheckTile == kUnitState.TileLocation)
Tiles code is consistently performance-intensive enough for Firaxis to have created the following function in `Helpers.uc` (and a few more):

```
static native function int FindTileInList(TTile Tile, const out array<TTile> List);
```

I think this can definitely come in useful here.

2021-02-07 21:51 UTC, robojumper commented
Also this has merge conflicts.

2021-04-07 08:56 UTC, pledbrook commented
I've merged @Grobobobo 's changes into the main commit and rebased against `master` to help with a clean merge.

2021-04-07 09:08 UTC, robojumper approved these changes

2021-04-07 09:53 UTC, pledbrook commented
Can confirm that the fix still seems to be working after the switch to using the native function.

2021-05-24 08:35 UTC, merged