Added inline docs for Issue #62.
X2CommunityCore/X2WOTCCommunityHighlander pull request #938
Opened 2021-01-08 21:01 UTC by Iridar

Closes #62. This issue has been implemented ages ago, this PR just adds documentation for it.

2021-01-11 22:26 UTC, Iridar commented
Should this PR have a separate commit for docs for each issue, or should I squash it?

2021-01-11 22:51 UTC, robojumper requested changes
One commit per issue is fine.

I'm now a bit unsure about our handling of `inout` vs `out`; I'd say it needs to be `inout` when the default value in the tuple potentially has a different value than the data type's default value just to make it so that the auto-generated event listener preserves the default value.

Like, this should be avoided (from the github-actions comment):

```
	local int iClipSize;

	ItemState = XComGameState_Item(EventSource);
	Tuple = XComLWTuple(EventData);

	// Your code here

	Tuple.Data[0].i = iClipSize;
```

because an unmodified listener will now set the clip size to 0 :)

2021-01-11 22:51 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
> +	///EventData: [out int iClipSize],
```suggestion
	///EventData: [inout int iClipSize],
```

2021-01-11 22:51 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2SitRepTemplate.uc
> +///EventData: [out bool bMeetsRequirements, in XComGameState_MissionSite MissionState],
```suggestion
///EventData: [inout bool bMeetsRequirements, in XComGameState_MissionSite MissionState],
```

2021-01-11 22:51 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
> +///EventData: [out bool bCanTechBeInspired],
```suggestion
///EventData: [inout bool bCanTechBeInspired],
```

2021-01-11 22:51 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_InteractiveObject.uc
> +///EventData: [out bool bAllowInteractHack, in XComGameState_Unit HackingUnit],
```suggestion
///EventData: [inout bool bAllowInteractHack, in XComGameState_Unit HackingUnit],
```

2021-01-11 22:51 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +	///EventData: [out bool bShowPromotionIcon],
```suggestion
	///EventData: [inout bool bShowPromotionIcon],
```

2021-01-11 23:03 UTC, robojumper approved these changes
Only small style nits now.

2021-01-11 23:03 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHumanPawn.uc
> +	/// Allow this function to work with new deco slots added with Anarchy Children and WOTC.
```suggestion
	/// Allow `bForcedAppearance` to work with new deco slots added with Anarchy Children and WOTC.
```

2021-01-11 23:03 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIGroup.uc
> +		/// Allow mods to override the LoP anchor point for the encounter zone. By
```suggestion
		/// This allows mods to override the LoP anchor point for the encounter zone. By
```

2021-01-11 23:11 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_LoadoutItem.uc
> +	///	Allows armory UI to highlight the item the player needs to build during the tutorial even if it's not a medkit.
Pulled the rug from under this suggestion by committing previous suggestions, had to do this one locally first.

2021-01-11 23:25 UTC, Iridar commented
> One commit per issue is fine.

Okay, I'll squash only the "fix" types of commits then.

2021-01-12 00:59 UTC, Iridar commented
All done. These are all the issues I intend to document for now, other open issues with need-docs label put me too far out of my element.

2021-01-12 01:02 UTC, Iridar commented
@pledbrook 
@Xymanek 
@MrNiceUK 
@shiremct
This PR contains docs for Issues resolved by you, please take a look to make sure the docs are correct, as my understanding in some of the more niche issues is less than perfect.

I would also encourage you to file docs for your Issues not covered by this PR yourselves; I did not cover them because they are too far out of my specialty.

2021-02-07 13:17 UTC, merged