Add PostRollForTrainingCenterAbilities event
X2CommunityCore/X2WOTCCommunityHighlander pull request #949
Opened 2021-01-13 02:31 UTC by Iridar

Closes #815

I have tested this to be working fine for a typical use case, although for some reason the event is triggered twice for each soldier. If I make changes to the `AbilityTree` the first time, the changes are reflected when the event is triggered the second time. This should probably be reflected in the docs.

Here's log output from a quick dumb test that replaces `RapidFire` with `Reaper` in the `AbilityTree` row with the Training Center abilities:
```
[0089.94] IRITEST: PostRollForTrainingCenterAbilities triggered for: Lucy Wood
[0089.94] IRITEST: Lucy Wood 0 RapidFire
[0089.94] IRITEST: Replacing Rapid Fire with Reaper
[0089.94] IRITEST: Lucy Wood 1 BulletShred
[0089.94] IRITEST: PostRollForTrainingCenterAbilities triggered for: Lucy Wood
[0089.94] IRITEST: Lucy Wood 0 Reaper
[0089.94] IRITEST: Lucy Wood 1 BulletShred
```
Also, somewhat unconventionally, the event trigger passes `none` as `EventData`; the event has nothing to put there at this time. 
I was thinking we could keep it `none` for now, and potentially put something into it later if we have a use for it.

2021-02-07 12:21 UTC, robojumper approved these changes

2021-02-07 19:39 UTC, robojumper requested changes
Actually, I think you should move the `TriggerEvent` call to inside of the `if` block. `RollForTrainingCenterAbilities` is idempotent and can be called any number of times, and only does work the first time, so the event should only be triggered once.

2021-02-08 08:54 UTC, Iridar commented
> Actually, I think you should move the `TriggerEvent` call to inside of the `if` block. `RollForTrainingCenterAbilities` is idempotent and can be called any number of times, and only does work the first time, so the event should only be triggered once.

Yeah, that makes a lot of sense. Doneso. Also added `notemplate` to the event docs, since my docs already have an example. Is my usage correct?

2021-02-08 08:56 UTC, robojumper commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +		/// EventSource: inout XComGameState_Unit (UnitState),
```suggestion
		/// EventSource: XComGameState_Unit (UnitState),
```

2021-02-08 08:59 UTC, Iridar commented
Right, sorry, I forgot that we do `inout` stuff only for the Tuple now.

2021-02-08 13:43 UTC, Iridar commented
On discord, robojumper has raised a rightful concern that for event listeners it would be hard to determine which of the perks in the `AbilityTree` are Training Center, and which have been there before. We discussed a couple of options of accomplishing that, such as going back to history and examining the prior Unit State, but I just realized two tings:

1) Since training center abilities are generated right then and there, just before the event trigger, we could keep a list of the training center perks that were added, and pass it to the event trigger. Although it's an array of `SoldierClassAbilityType` structs, so passing them to the event trigger will require some sort of hack, like creating a copy of the Unit State.

2) At that point, wouldn't it be better to trigger the event after the list of training center perks has been generated, but before they are inserted into the ability tree? So that mods can alter the list of the eligible training center perks instead of the Ability Tree. This also removes [this concern](https://www.reddit.com/r/xcom2mods/wiki/index/events#wiki_important_note), and if mods want to specifically alter the AbilityTree *after* the perks have already been added to the AbilityTree, they can listen to the same event with `ELD_OnStateSubmitted` instead.

2022-01-19 20:01 UTC, Iridar commented
Closing, implemented differently in another PR.

2022-01-19 20:01 UTC, closed without merging