Add event to override ability icon color
X2CommunityCore/X2WOTCCommunityHighlander pull request #957
Opened 2021-01-14 02:04 UTC by Iridar

Closes #400 by adding docs for it

A rebased and updated version of #750

Closes #749

2021-01-14 02:05 UTC, Iridar commented
Absolutely nothing here is done, please don't review just yet.

2021-01-14 03:03 UTC, Iridar commented
Ready for review now. Please give a thorough proofreading to new docs, because my eye has gone completely blurry.
The new override event is confirmed to be working. 

@VampireMonkey 's heart was in the right place when it came to storing icon color in local variables and then triggering both overrides before actually using the icon color variables, but I opted to create a separate new event to completely preserve the backwards compatibility, and to make code easier to read and understand and interact with.

2021-02-09 06:55 UTC, Iridar commented
robojumper said they're not qualified to review this, so somebody else will have to pick up the mantle.

2021-02-20 08:37 UTC, Xymanek requested changes

2021-02-20 08:37 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +	Icon.EnableMouseAutomaticColor(IconColor, ForegroundColor);
Why was this moved outside of `if (AbilityTemplate != None)`?

2021-02-20 08:39 UTC, Xymanek commented
I do not have a use case for this, so I might be missing something, but from BC perspective this is 👍

2021-02-27 11:07 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +	Icon.EnableMouseAutomaticColor(IconColor, ForegroundColor);
A mistake. Will fix. Thanks for noticing.

2021-02-27 11:12 UTC, Iridar commented
I've noticed there are two `if (AbilityTemplate != none)` checks in that single function. This can be probably refactored to save an extra CPU cycle, but at this point I don't want to touch this.

2021-05-24 10:11 UTC, pledbrook reviewed
Mostly suggested documentation changes. I'll leave it up to you whether you want to change the suggested variable name (`IconColor` -> `BackgroundColor`).

2021-05-24 10:11 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +/// This event has been deprecated by an improved version: [OverrideAbilityIconColorImproved](../tactical/OverrideAbilityIconColorImproved.md)
```suggestion
/// This event has been deprecated and should no longer be used. It is kept for
/// backwards compatibility. Use [OverrideAbilityIconColorImproved](../tactical/OverrideAbilityIconColorImproved.md) isntead.
```

2021-05-24 10:11 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +/// HL-Docs: feature:OverrideAbilityIconColorImproved; issue:749; tags:tactical
```suggestion
/// HL-Docs: feature:OverrideAbilityIconColorImproved; issue:749; tags:tactical,compatibility
```

2021-05-24 10:11 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +/// set by the deprecated event: [OverrideAbilityIconColor](../tactical/OverrideAbilityIconColor.md)
```suggestion
```

2021-05-24 10:11 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +/// ```
```suggestion
/// ```
///
/// ## Compatibility
/// This event takes precedence over the deprecated event [OverrideAbilityIconColor](../tactical/OverrideAbilityIconColor.md),
/// so any listener that changes ability icon colors will always overwrite any
/// changes made by listeners of the deprecated event.
```

2021-05-24 10:11 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +static final function TriggerOverrideAbilityIconColorImproved(XComGameState_Ability Ability, bool IsObjective, out string IconColor, out string ForegroundColor)
I think it would be slightly better if `IconColor` was `BackgroundColor` for clarity and consistency with the docs.

```suggestion
static final function TriggerOverrideAbilityIconColorImproved(XComGameState_Ability Ability, bool IsObjective, out string BackgroundColor, out string ForegroundColor)
```

2021-05-24 10:11 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +	OverrideTuple.Data[1].s = IconColor;
```suggestion
	OverrideTuple.Data[1].s = BackgroundColor; 
```

2021-05-24 10:11 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +	IconColor = OverrideTuple.Data[1].s;
```suggestion
	BackgroundColor= OverrideTuple.Data[1].s;
```

2021-05-24 11:44 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +/// set by the deprecated event: [OverrideAbilityIconColor](../tactical/OverrideAbilityIconColor.md)
TBH I'd rather keep this note, it's just a couple of extra lines.

2021-05-24 11:46 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +static final function TriggerOverrideAbilityIconColorImproved(XComGameState_Ability Ability, bool IsObjective, out string IconColor, out string ForegroundColor)
Yeah I don't mind doing that for consistency, but I'll probably update docs to make it clear what is background and foreground in this context. Having it as "IconColor" kinda self-explains that *this* is the value you want to change to recolor the icon. Without that distinction it might be tough to figure what needs changing.

2021-05-24 12:13 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +static final function TriggerOverrideAbilityIconColorImproved(XComGameState_Ability Ability, bool IsObjective, out string IconColor, out string ForegroundColor)
Interesting. I don't know what "icon colour" means if you also have foreground colour. I guess this is because icons are inverted somewhat, i.e. they work on the basis of the background bleeding through the stencil that is the icon image. Is that correct? So what's foreground colour for?

2021-05-24 12:18 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +static final function TriggerOverrideAbilityIconColorImproved(XComGameState_Ability Ability, bool IsObjective, out string IconColor, out string ForegroundColor)
Basically all icons have two colors, it's just that the second - "foreground" - is normally black, so you don't think about it as a separate color, but this event does allow changing it.

2021-05-24 13:06 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +	BackgroundColor= OverrideTuple.Data[1].s;
My bad, lost a space:
```suggestion
	BackgroundColor = OverrideTuple.Data[1].s;
```
Once that's added, I'll approve.

2021-05-24 13:13 UTC, Iridar commented
I'll be adjusting docs and squashing this.

2021-05-24 16:34 UTC, Iridar commented
Updated docs, rebased onto master, squashed. Should be good to go.

2021-05-26 10:29 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
> +/// backwards compatibility. Use [OverrideAbilityIconColorImproved](../tactical/OverrideAbilityIconColorImproved.md) isntead.
```suggestion
/// backwards compatibility. Use [OverrideAbilityIconColorImproved](../tactical/OverrideAbilityIconColorImproved.md) instead.
```

2021-05-26 10:36 UTC, pledbrook approved these changes
Looks good. I'll approve, but there is a small typo in the docs that I've pointed out in a separate comment.

2021-05-26 12:01 UTC, Iridar commented
> Looks good. I'll approve, but there is a small typo in the docs that I've pointed out in a separate comment.

Fixed and squashed, thanks.

2021-05-28 09:58 UTC, merged