Make TypicalAbility_BuildVisualization get AbilityState and SourceWeapon from VisualizeGameState when possible
X2CommunityCore/X2WOTCCommunityHighlander pull request #958
Opened 2021-01-14 04:27 UTC by Iridar

Closes #879

I've added `none` checks and made the code fallback on getting these state objects from history if the code fails to retrieve them from the `VisualizeGameState` - presumably because the `BuildGameStateFn()` did not add them to the Game State for whatever reason. 

So best case scenario, this fixes the bug, and worst case scenario, fallbacks on vanilla behavior anyway.

2021-01-14 04:28 UTC, Iridar commented
Note that this is a very obscure, low priority bug that manifests only when you do something hacky, like make hot changes to AbilityState / ItemState after the ability has been activated, but before it was visualized. Not sure that anybody will have a use case for this fix besides myself.

2021-02-07 12:11 UTC, robojumper requested changes
I don't think we should check the game state itself at all -- instead, we should ask the History for the object at a certain point in time, e.g.:

    History.GetGameStateForObjectID(AbilityContext.AbilityRef.ObjectId, , VisualizeGameState.HistoryIndex);

2021-02-08 09:13 UTC, Iridar commented
Makes sense. Accomplishes the same thing with less boilerplate. Done and tested, this at least doesn't break the base game abilities. Squashed.

2021-02-08 09:30 UTC, robojumper approved these changes

2021-02-11 11:07 UTC, Xymanek approved these changes

2021-05-24 08:36 UTC, merged