Add Configuration Options to Beta Strike's End Tactical Heal - Issue #917
X2CommunityCore/X2WOTCCommunityHighlander pull request #979
Opened 2021-02-26 20:46 UTC by daakru

Addresses #917

2021-02-27 08:56 UTC, Iridar requested changes
This PR looks kinda messy, for some reason touching a lot of the files not relevant to this PR, and looks like your feature branch needs to be rebased to the latest master before adding your changes.

2021-02-27 08:56 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> +;bDontUnequipCovertOps=true ; Uncomment to make soldiers on covert ops keep their gear even if ambush risk is 0
Looks like this is not supposed to be here.

2021-02-27 08:56 UTC, Iridar commented on X2WOTCCommunityHighlander/Config/XComGame.ini
> ++ValidReserveAPForUnitFlag = "pistoloverwatch"
Looks like this is not supposed to be here.

2021-02-27 08:56 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
> +
Please avoid modifying styling for functions not relevant to your PR.

2021-02-27 18:05 UTC, daakru commented
I'm not sure what I messed up with my documentation formatting.

2021-02-27 18:34 UTC, robojumper commented
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/979/checks?check_run_id=1994924023
```
error: ./X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc:2619: missing key `tags`
note: use `tags:` to specify an empty tag list
error: ./X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc:185: missing key `tags`
note: use `tags:` to specify an empty tag list
```

2021-02-27 18:44 UTC, daakru commented
> https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/979/checks?check_run_id=1994924023
> 
> ```
> error: ./X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc:2619: missing key `tags`
> note: use `tags:` to specify an empty tag list
> error: ./X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc:185: missing key `tags`
> note: use `tags:` to specify an empty tag list
> ```

Oh, thanks! I checked in the right place but didn't notice those at the top.

2021-03-11 02:44 UTC, Iridar approved these changes
Looks good to me overall.

2021-03-11 02:44 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +		SWHeal = class'CHHelpers'.default.fBetaStrikeEndTacticalHeal_Fraction == 0.0f ?
Styling nip: in the future preferably use `if() {} else {}` syntax in cases like this. Also, this line prevents `0.0f` from being a valid config value, when, logically, it should be. 

It is allowed to add and initialize new config variables. So you could uncomment the entry `fBetaStrikeEndTacticalHeal_Fraction = 0.5f` entry in the config file, and keep it in there as the default value. 

Same goes for `bDisableBetaStrikeEndTacticalHeal` that you could default to true. 

Although I suppose having it written like this makes it easier to make a mod that will disable this healing feature, so I guess this is fine too. It's not like there's any extra value in having `0.0f` as a valid value when you could just disable the heal altogether, achieving the same.

2021-05-24 09:32 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +				SWHeal = FFLoor(SWHeal);
This is unfair to modders and players who choose one of the many options from `ECHRounding_Type`, only for the game to quietly (no one's going to notice a redscreen when playing a non-debug version of the game) ignore the setting. I'm also not sure it's worth introducing rounding behaviours when no other part of the game has that configurable as far as I'm aware.

I'm also somewhat surprised this doesn't support `eCHRounding_None`, since truncation is pretty commonly applied in XCOM 2.

Anyway, need to chat with folks about whether this is a good idea or not.

2021-05-24 09:32 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +		/// HL-Docs: ref:ECHRounding_Type
Text alignment seems to be off here.

2021-05-26 08:55 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +				SWHeal = FFLoor(SWHeal);
Iridar has argued that it's fine to add support for such rounding types, but in that case, a function should be added that will apply the relevant rounding to a floating-point number based on the requested rounding type. Something like `CHHelpers.RoundWithType(float Number, ECH_RoundingType Type)`.

2021-05-26 08:59 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +				SWHeal = FFLoor(SWHeal);
Yeah I've been meaning to take care of it myself, but I'm not sure if I'll have access to daakru's branch?

2021-06-03 08:28 UTC, Iridar commented
Putting this on pause until @daakru implements a `CHHelpers.RoundWithType` function, and adjusts the PR and docs to reflect that.

2021-08-16 05:30 UTC, pledbrook commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
> +				SWHeal = FFLoor(SWHeal);
You don't need write access. You can pull daakru's changes into a local branch in your local repo, make additional changes, and then either merge direct to `master` as part of the "merging" process, or create a new remote branch and submit a new PR that supersedes this one.

2023-05-21 07:54 UTC, Iridar commented
Since the author has been AWOL for over two years, I'm archiving this.

2023-05-21 07:54 UTC, closed without merging