Fix backwards compatibility breaks added by PR #910
X2CommunityCore/X2WOTCCommunityHighlander pull request #981
Opened 2021-02-27 10:27 UTC by Iridar

Closes #975

2021-03-23 09:37 UTC, Xymanek requested changes
You still need to adjust/fix

* `UITLE_SkirmishModeMenu.uc`
* `X2Action.uc`

2021-03-23 09:37 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
> +		}
The original was `if( Ability.GetMyTemplate() != none )`. Assuming `Ability == none`, we get

* `if( (none).GetMyTemplate() != none )`
  * `(none).GetMyTemplate()` gives `none`
* `if( none != none )`
* `if( false )`

As such, the `UnitVisualizer.GetPawn().AppendAbilityPerks( Ability.GetMyTemplate().GetPerkAssociationName() );` line was never invoked with the `Ability == none`, hence this else branch is incorrect

2021-03-23 09:37 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIImageChip.uc
> -	Highlight.SetX( BG.X - (PADDING_HIGHLIGHT * 0.5) );
Instead of outright removing the line, please comment it out with a small explanation of what happened here.

It's also a good idea (from BC perspective) to avoid reordering the calls, but in this particular case I can't see any potential issues from doing so, so I'm fine with the current approach

2021-03-23 09:37 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/UIImageChip.uc
> -	Highlight.SetY( BG.Y - (PADDING_HIGHLIGHT * 0.5) );
Same comment as above

2021-03-23 14:31 UTC, Iridar commented
@Xymanek thanks for the review, should be fixed now.

2021-03-24 09:10 UTC, Xymanek approved these changes

2021-03-24 09:11 UTC, merged