Add event to override squadsize achievement
X2CommunityCore/X2WOTCCommunityHighlander pull request #995
Opened 2021-05-19 17:12 UTC by cannonfodder1

Closes #994 
TODO: rename the event ID to something better
TODO: add highlander documentation

2021-05-21 10:38 UTC, Xymanek commented
Note that the tracking issue is currently hosting a discussion about the correct approach to implementing this feature

2021-06-03 08:40 UTC, Iridar commented
Please resolve the conflicts. Current `master` branch of the Highlander already includes `X2AchievemntTracker.uc`, so you no longer have to be adding this file. Ideally, this PR should be squashed to just one commit with your changes.

2021-06-04 05:33 UTC, cannonfodder1 commented
I rebased to resolve the merge conflicts, this PR should be ready for squash merge

2021-06-08 05:43 UTC, Iridar approved these changes

2021-06-08 05:43 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AchievementTracker.uc
> +		if (!HasIncreasedSquadSize()) // Beat the game on Classic+ difficulty without buying a Squad Size upgrade
Minor nitpick; this could use a `// Issue #994` tag.

2021-06-09 08:15 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AchievementTracker.uc
> +		if (!HasIncreasedSquadSize()) // Beat the game on Classic+ difficulty without buying a Squad Size upgrade
And a `HL-Docs: ref` comment as well

2021-06-10 02:45 UTC, cannonfodder1 commented
I'm not quite sure how that unforgivable oversight happened, because I caught it today immediately upon compile and there's been three commits since the renaming of that function. I remember our custom CHL was crapping out and not allowing me to compile at some point during the development of this, but I thought I fixed it a while ago. Even if compilation was broken for three whole commits, why did I commit them without compiling?

2021-06-10 13:45 UTC, Iridar approved these changes
Looks good to me now.

2021-06-10 15:58 UTC, Xymanek requested changes

2021-06-10 15:58 UTC, Xymanek commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AchievementTracker.uc
> +static function bool AllowNoSquadSizeUpgradeAchievement()
```suggestion
private static function bool AllowNoSquadSizeUpgradeAchievement()
```

2021-06-10 16:06 UTC, Iridar commented on X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AchievementTracker.uc
> +static function bool AllowNoSquadSizeUpgradeAchievement()
Perhaps `final` instead? In case a mod wants to check this for whatever reason.

2021-06-11 06:09 UTC, Xymanek approved these changes

2021-06-11 06:09 UTC, merged